#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>


procedure start
begin
	variable LVar0 := 0;
	if (script_action == map_enter_proc) then begin
		LVar0 := create_object_sid(4, 0, 0, -1);
		add_obj_to_inven(dude_obj, LVar0);
		LVar0 := create_object_sid(18, 0, 0, -1);
		add_obj_to_inven(dude_obj, LVar0);
		LVar0 := create_object_sid(31, 0, 0, -1);
		add_obj_to_inven(dude_obj, LVar0);
		LVar0 := create_object_sid(40, 0, 0, -1);
		add_obj_to_inven(dude_obj, LVar0);
	end
	else begin
		if (script_action == map_exit_proc) then begin
		end
		else begin
			if (script_action == map_update_proc) then begin
				if (elevation(dude_obj) == 0) then begin
					set_light_level(1);
				end
				else begin
					set_light_level(100);
				end
			end
			else begin
				if (script_action == timed_event_proc) then begin
				end
			end
		end
	end
end