#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure do_dialogue;
procedure alya00;
procedure alya01;
procedure alya02;
procedure alya03;
procedure alya04;
procedure alya05;
procedure alya06;
procedure alya07;
procedure alya08;
procedure alya09;
procedure alya10;
procedure alyaend;
procedure talk_p_proc;
procedure combat;
procedure Critter_Action;
procedure damage_p_proc;

variable HOSTILE;
variable initialized1;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure start
begin
	if (not(initialized1)) then begin
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 6);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_RAIDER_GUARD);
		initialized1 := 1;
	end
	if (script_action == talk_proc) then begin
		call talk_p_proc;
	end
	else begin
		if (script_action == timed_event_proc) then begin
			if (tile_distance_objs(self_obj, dude_obj) < 8) then begin
				call combat;
			end
		end
		else begin
			if (script_action == pickup_proc) then begin
				HOSTILE := 1;
			end
			else begin
				if (script_action == critter_proc) then begin
					call Critter_Action;
					if (HOSTILE) then begin
						HOSTILE := 0;
						attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
					end
				end
				else begin
					if (script_action == look_at_proc) then begin
						script_overrides;
						display_msg(message_str(SCRIPT_ALYA, 100));
					end
					else begin
						if (script_action == damage_proc) then begin
							call damage_p_proc;
						end
						else begin
							if (script_action == destroy_proc) then begin
								if (source_obj == dude_obj) then begin
									if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
										set_global_var(GVAR_BERSERKER_REPUTATION, 1);
										set_global_var(GVAR_CHAMPION_REPUTATION, 0);
									end
									if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
										set_global_var(GVAR_CHAMPION_REPUTATION, 1);
										set_global_var(GVAR_BERSERKER_REPUTATION, 0);
									end
									set_global_var(GVAR_BAD_MONSTER, global_var(GVAR_BAD_MONSTER) + 1);
									if ((global_var(GVAR_BAD_MONSTER) % 6) == 0) then begin
										set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 1);
									end
								end
								set_global_var(GVAR_ENEMY_RAIDERS, 1);
								set_global_var(GVAR_GARLS_FRIEND, 0);
								set_global_var(GVAR_TOTAL_RAIDERS, global_var(GVAR_TOTAL_RAIDERS) - 1);
							end
						end
					end
				end
			end
		end
	end
end

procedure do_dialogue
begin
	set_local_var(3, 1);
	call Get_Reaction;
	start_gdialog(SCRIPT_ALYA, self_obj, 4, -1, -1);
	gsay_start;
	if (local_var(4) == 5) then begin
		call alya10;
	end
	else begin
		set_local_var(4, local_var(4) + 1);
		call alya00;
	end
	gsay_end;
	end_dialogue;
end

procedure alya00
begin
	gsay_reply(SCRIPT_ALYA, 101);
	if ((global_var(GVAR_RESCUE_TANDI) == 1) and (global_var(GVAR_TALKED_ABOUT_TANDI) == 1)) then begin
		giq_option(4, SCRIPT_ALYA, 102, alya01, NEUTRAL_REACTION);
	end
	if (dude_is_male) then begin
		giq_option(4, SCRIPT_ALYA, 103, alya02, NEUTRAL_REACTION);
	end
	giq_option(4, SCRIPT_ALYA, 104, alya03, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_ALYA, 105, alyaend, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_ALYA, 106, alya05, NEUTRAL_REACTION);
end

procedure alya01
begin
	gsay_message(SCRIPT_ALYA, 107, NEUTRAL_REACTION);
end

procedure alya02
begin
	gsay_message(SCRIPT_ALYA, 108, NEUTRAL_REACTION);
	call combat;
end

procedure alya03
begin
	gsay_reply(SCRIPT_ALYA, 109);
	giq_option(4, SCRIPT_ALYA, 110, alya04, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_ALYA, 111, alya09, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_ALYA, 112, alyaend, NEUTRAL_REACTION);
end

procedure alya04
begin
	gsay_reply(SCRIPT_ALYA, 113);
	giq_option(4, SCRIPT_ALYA, 114, alya06, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_ALYA, 115, alya08, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_ALYA, 116, alyaend, NEUTRAL_REACTION);
end

procedure alya05
begin
	gsay_message(SCRIPT_ALYA, 117, NEUTRAL_REACTION);
end

procedure alya06
begin
	gsay_reply(SCRIPT_ALYA, 118);
	giq_option(4, SCRIPT_ALYA, 119, alya07, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_ALYA, 120, combat, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_ALYA, 121, alyaend, NEUTRAL_REACTION);
end

procedure alya07
begin
	gsay_message(SCRIPT_ALYA, 122, NEUTRAL_REACTION);
	call combat;
end

procedure alya08
begin
	gsay_message(SCRIPT_ALYA, 123, NEUTRAL_REACTION);
	add_timer_event(self_obj, game_ticks(15), 1);
end

procedure alya09
begin
	gsay_message(SCRIPT_ALYA, 124, NEUTRAL_REACTION);
end

procedure alya10
begin
	gsay_message(SCRIPT_ALYA, 125, NEUTRAL_REACTION);
end

procedure alyaend
begin
end

procedure talk_p_proc
begin
	if (global_var(GVAR_MISTAKEN_ID) == 1) then begin
		float_msg(self_obj, message_str(SCRIPT_GENRAIDR, random(102, 106)), FLOAT_MSG_YELLOW);
	end
	else begin
		call do_dialogue;
	end
end

procedure combat
begin
	if (global_var(GVAR_MISTAKEN_ID) == 1) then begin
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 87);
	end
	HOSTILE := 1;
end

procedure Critter_Action
begin
	variable LVar0 := 0;
	if (global_var(GVAR_TANDI_STATUS) == 2) then begin
		set_global_var(GVAR_ENEMY_RAIDERS, 1);
	end
	else begin
		if (global_var(GVAR_MISTAKEN_ID)) then begin
			set_global_var(GVAR_ENEMY_RAIDERS, 0);
			if (tile_distance_objs(self_obj, dude_obj) < 3) then begin
				LVar0 := tile_num_in_direction(tile_num(self_obj), random(0, 5), 3);
				if (tile_distance(tile_num(self_obj), LVar0) > 2) then begin
					if (random(0, 9) == 0) then begin
						float_msg(self_obj, message_str(SCRIPT_GENRAIDR, random(102, 106)), FLOAT_MSG_YELLOW);
					end
					animate_move_obj_to_tile(self_obj, LVar0, ANIMATE_WALK);
				end
			end
		end
		else begin
			if (global_var(GVAR_TANDI_ESCAPE)) then begin
				set_global_var(GVAR_ENEMY_RAIDERS, 1);
			end
			if (obj_can_see_obj(self_obj, dude_obj)) then begin
				if (global_var(GVAR_RAID_LOOTING)) then begin
					set_global_var(GVAR_ENEMY_RAIDERS, 1);
				end
			end
			if (map_var(2) == 1) then begin
				set_global_var(GVAR_ENEMY_RAIDERS, 1);
			end
		end
	end
	if (global_var(GVAR_ENEMY_RAIDERS) and obj_can_see_obj(self_obj, dude_obj)) then begin
		HOSTILE := 1;
	end
	if (tile_distance_objs(self_obj, dude_obj) > 12) then begin
		HOSTILE := 0;
	end
end

procedure damage_p_proc
begin
	if (global_var(GVAR_MISTAKEN_ID) == 0) then begin
		set_global_var(GVAR_ENEMY_RAIDERS, 1);
	end
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end