#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>

variable test;
variable damage;


procedure start
begin
	if (script_action == use_obj_on_proc) then begin
		if (obj_pid(obj_being_used_with) == 85) then begin
			script_overrides;
			test := roll_vs_skill(dude_obj, 11, 0);
			if (is_success(test)) then begin
				display_msg(message_str(SCRIPT_BLAST, 100));
				give_exp_points(1);
				display_msg(message_str(SCRIPT_BLAST, 103));
			end
			else begin
				if (is_critical(test)) then begin
					display_msg(message_str(SCRIPT_BLAST, 101));
					damage := random(10, 40);
					critter_dmg(dude_obj, damage, 0);
				end
				else begin
					display_msg(message_str(SCRIPT_BLAST, 102));
				end
			end
		end
	end
end