#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>


procedure start
begin
	if (script_action == spatial_proc) then begin
		if (obj_type(source_obj) == dude_obj) then begin
			if (local_var(4) == 0) then begin
				if (get_critter_stat(dude_obj, 4) > 6) then begin
					display_msg(message_str(SCRIPT_BLKROM, 100));
				end
				else begin
					display_msg(message_str(SCRIPT_BLKROM, 101));
				end
				set_local_var(4, 1);
			end
		end
	end
end