#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>

variable rndx;


procedure start
begin
	if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
		script_overrides;
		rndx := random(1, 3);
		if (rndx == 1) then begin
			display_msg(message_str(SCRIPT_BONEBODY, 100));
		end
		else begin
			if (rndx == 2) then begin
				display_msg(message_str(SCRIPT_BONEBODY, 101));
			end
			else begin
				if (rndx == 3) then begin
					display_msg(message_str(SCRIPT_BONEBODY, 102));
				end
			end
		end
	end
end