#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure use_p_proc;
procedure look_at_p_proc;
procedure talk_p_proc;
procedure bull01;
procedure bull02;
procedure bull03;
procedure bull04;


procedure start
begin
	if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == use_proc) then begin
			call use_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
		end
	end
end

procedure use_p_proc
begin
	dialogue_system_enter;
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_BULLBORD, 100));
end

procedure talk_p_proc
begin
	set_map_var(43, 1);
	start_gdialog(SCRIPT_BULLBORD, self_obj, 4, -1, -1);
	gsay_start;
	call bull01;
	gsay_end;
	end_dialogue;
end

procedure bull01
begin
	gsay_reply(SCRIPT_BULLBORD, 101);
	giq_option(0, SCRIPT_BULLBORD, 105, bull02, NEUTRAL_REACTION);
end

procedure bull02
begin
	gsay_reply(SCRIPT_BULLBORD, 102);
	giq_option(0, SCRIPT_BULLBORD, 105, bull03, NEUTRAL_REACTION);
end

procedure bull03
begin
	gsay_reply(SCRIPT_BULLBORD, 103);
	giq_option(0, SCRIPT_BULLBORD, 105, bull04, NEUTRAL_REACTION);
end

procedure bull04
begin
	gsay_message(SCRIPT_BULLBORD, 104, NEUTRAL_REACTION);
end