#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>

variable test;


procedure start
begin
	if (script_action == spatial_proc) then begin
		if (source_obj == dude_obj) then begin
			if (local_var(0) == 0) then begin
				set_local_var(0, 1);
				test := do_check(dude_obj, 1, has_trait(0, dude_obj, 0) - 2);
				if (is_success(test)) then begin
					if (is_critical(test)) then begin
						display_msg(message_str(SCRIPT_BVLIVE, 100));
					end
					else begin
						display_msg(message_str(SCRIPT_BVLIVE, 101));
					end
				end
			end
		end
	end
end