#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>


procedure start
begin
	if (script_action == spatial_proc) then begin
		if (source_obj == dude_obj) then begin
			if (local_var(0) == 0) then begin
				set_local_var(0, 1);
				if (is_success(do_check(dude_obj, 4, 0))) then begin
					display_msg(message_str(SCRIPT_BVLIB, 100));
				end
				if (is_success(do_check(dude_obj, 1, has_trait(0, dude_obj, 0)))) then begin
					display_msg(message_str(SCRIPT_BVLIB, 101));
				end
			end
		end
	end
end