#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>


variable GVar0;
variable GVar1 := 1;
variable GVar2;

procedure start;
#include <push.h>
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure Cheater00a;
procedure Cheater00;
procedure Cheater01;
procedure Cheater02;
procedure Cheater03;
procedure Cheater04;
procedure Cheater05;
procedure Cheater06;
procedure Cheater06a;
procedure Cheater06b;
procedure Cheater06c;
procedure Cheater06d;
procedure Cheater06e;
procedure Cheater07;
procedure Cheater08;
procedure CheaterEnd;
procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;


procedure start
begin
	if (GVar1) then begin
		GVar1 := 0;
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 84);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_PLAYER);
	end
	if (script_action == look_at_proc) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == pickup_proc) then begin
			call pickup_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
			else begin
				if (script_action == critter_proc) then begin
					call critter_p_proc;
				end
				else begin
					if (script_action == destroy_proc) then begin
						call destroy_p_proc;
					end
				end
			end
		end
	end
end

procedure combat
begin
	GVar0 := 1;
end

procedure critter_p_proc
begin
	if (GVar0) then begin
		GVar0 := 0;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		GVar0 := 1;
	end
end

procedure talk_p_proc
begin
	call Get_Reaction;
	start_gdialog(SCRIPT_CHEATER, self_obj, 4, -1, -1);
	gsay_start;
	call Cheater00a;
	gsay_end;
	end_dialogue;
end

procedure destroy_p_proc
begin
	if (source_obj == dude_obj) then begin
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 7) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg("You see a cheating person.");
end

procedure Cheater00a
begin
	gsay_reply(SCRIPT_CHEATER, "How may I Cheat you today?");
	giq_option(1, SCRIPT_CHEATER, "Experience Points.", Cheater00, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "Damage.", Cheater06, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "Poison", Cheater07, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "Radiation", Cheater08, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "Nothing.", CheaterEnd, NEUTRAL_REACTION);
end

procedure Cheater00
begin
	gsay_reply(SCRIPT_CHEATER, "How much Exp Points do you want?");
	giq_option(1, SCRIPT_CHEATER, "500", Cheater01, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "1000", Cheater02, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "5000", Cheater03, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "10000", Cheater04, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "20000", Cheater05, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "Nevermind", CheaterEnd, NEUTRAL_REACTION);
end

procedure Cheater01
begin
	give_exp_points(500);
	gsay_message(SCRIPT_CHEATER, "Ok, you have them.", NEUTRAL_REACTION);
	call Cheater00;
end

procedure Cheater02
begin
	give_exp_points(1000);
	gsay_message(SCRIPT_CHEATER, "Ok, you have them.", NEUTRAL_REACTION);
	call Cheater00;
end

procedure Cheater03
begin
	give_exp_points(5000);
	gsay_message(SCRIPT_CHEATER, "Ok, you have them.", NEUTRAL_REACTION);
	call Cheater00;
end

procedure Cheater04
begin
	give_exp_points(10000);
	gsay_message(SCRIPT_CHEATER, "Ok, you have them.", NEUTRAL_REACTION);
	call Cheater00;
end

procedure Cheater05
begin
	give_exp_points(20000);
	gsay_message(SCRIPT_CHEATER, "Ok, you have them.", NEUTRAL_REACTION);
	call Cheater00;
end

procedure Cheater06
begin
	gsay_reply(SCRIPT_CHEATER, "How might I abuse you today?");
	giq_option(1, SCRIPT_CHEATER, "Cripple Left Leg", Cheater06a, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "Cripple Right Leg", Cheater06b, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "Cripple Left Arm", Cheater06c, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "Cripple Right Arm", Cheater06d, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "Blind Me ", Cheater06e, NEUTRAL_REACTION);
	giq_option(1, SCRIPT_CHEATER, "Don't hurt me.", Cheater00a, NEUTRAL_REACTION);
end

procedure Cheater06a
begin
	critter_injure(dude_obj, 4);
	gsay_message(SCRIPT_CHEATER, "[Grinning Visciously] I was happy to Help you", NEUTRAL_REACTION);
	call Cheater00a;
end

procedure Cheater06b
begin
	critter_injure(dude_obj, 8);
	gsay_message(SCRIPT_CHEATER, "[Grinning Visciously] I was happy to Help you", NEUTRAL_REACTION);
	call Cheater00a;
end

procedure Cheater06c
begin
	critter_injure(dude_obj, 4);
	gsay_message(SCRIPT_CHEATER, "[Grinning Visciously] I was happy to Help you", NEUTRAL_REACTION);
	call Cheater00a;
end

procedure Cheater06d
begin
	critter_injure(dude_obj, 16);
	gsay_message(SCRIPT_CHEATER, "[Grinning Visciously] I was happy to Help you", NEUTRAL_REACTION);
	call Cheater00a;
end

procedure Cheater06e
begin
	critter_injure(dude_obj, 32);
	gsay_message(SCRIPT_CHEATER, "[Grinning Visciously] I was happy to Help you", NEUTRAL_REACTION);
	call Cheater00a;
end

procedure Cheater07
begin
	poison(dude_obj, 10);
	gsay_message(SCRIPT_CHEATER, "[Hands you a Burrito Supreme] Enjoy your Grade D Beef.", NEUTRAL_REACTION);
	call Cheater00a;
end

procedure Cheater08
begin
	radiation_inc(dude_obj, 50);
	gsay_message(SCRIPT_CHEATER, "Now you glow like a 50 watt light bulb.", NEUTRAL_REACTION);
	call Cheater00a;
end

procedure CheaterEnd
begin
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) > 34) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) > 34) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	GVar2 := message_str(SCRIPT_MODREACT, random(100, 105));
end