#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>

variable rndx;


procedure start
begin
	if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
		script_overrides;
		rndx := random(1, 4);
		if (global_var(GVAR_BROTHERHOOD_OF_STEEL) == 2) then begin
			if (rndx == 1) then begin
				display_msg(message_str(SCRIPT_DEADBRO, 100));
			end
			else begin
				if (rndx == 2) then begin
					display_msg(message_str(SCRIPT_DEADBRO, 101));
				end
				else begin
					if (rndx == 3) then begin
						display_msg(message_str(SCRIPT_DEADBRO, 102));
					end
					else begin
						if (rndx == 4) then begin
							display_msg(message_str(SCRIPT_DEADBRO, 103));
						end
					end
				end
			end
		end
		else begin
			if (rndx == 1) then begin
				display_msg(message_str(SCRIPT_DEADBRO, 104));
			end
			else begin
				if (rndx == 2) then begin
					display_msg(message_str(SCRIPT_DEADBRO, 105));
				end
				else begin
					if (rndx == 3) then begin
						display_msg(message_str(SCRIPT_DEADBRO, 106));
					end
				end
			end
		end
	end
end