#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure Deadguy00;
procedure Deadguy01;
procedure Deadguy02;
procedure Deadguy03;
procedure Deadguy04;
procedure Deadguy05;
procedure Deadguy06;
procedure Deadguy07;
procedure Deadguy08;
procedure DeadguyEnd;

variable hostile1;
variable Only_Once := 1;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure start
begin
	if (Only_Once) then begin
		Only_Once := 0;
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 41);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_HUB_PEASANTS);
	end
	if (script_action == look_at_proc) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == pickup_proc) then begin
			call pickup_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
			else begin
				if (script_action == critter_proc) then begin
					call critter_p_proc;
				end
				else begin
					if (script_action == destroy_proc) then begin
						call destroy_p_proc;
					end
				end
			end
		end
	end
end

procedure combat
begin
	hostile1 := 1;
end

procedure critter_p_proc
begin
	if (hostile1) then begin
		hostile1 := 0;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		hostile1 := 1;
	end
end

procedure talk_p_proc
begin
	call Get_Reaction;
	if (local_var(4) == 1) then begin
		call Deadguy02;
	end
	else begin
		set_local_var(4, 1);
		start_gdialog(SCRIPT_DEADGUY, self_obj, 4, -1, -1);
		gsay_start;
		call Deadguy00;
		gsay_end;
		end_dialogue;
	end
end

procedure destroy_p_proc
begin
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_DEADGUY, 100));
end

procedure Deadguy00
begin
	gsay_reply(SCRIPT_DEADGUY, 101);
	giq_option(4, SCRIPT_DEADGUY, 102, Deadguy01, BAD_REACTION);
	if (local_var(5) == 0) then begin
		giq_option(4, SCRIPT_DEADGUY, 103, Deadguy03, NEUTRAL_REACTION);
	end
	giq_option(4, SCRIPT_DEADGUY, 104, Deadguy07, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_DEADGUY, 105, Deadguy06, NEUTRAL_REACTION);
end

procedure Deadguy01
begin
	gsay_message(SCRIPT_DEADGUY, 106, NEUTRAL_REACTION);
end

procedure Deadguy02
begin
	float_msg(self_obj, message_str(SCRIPT_DEADGUY, 107), FLOAT_MSG_RED);
end

procedure Deadguy03
begin
	set_local_var(5, 1);
	item_caps_adjust(dude_obj, 20);
	gsay_reply(SCRIPT_DEADGUY, 108);
	giq_option(4, SCRIPT_DEADGUY, 109, DeadguyEnd, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_DEADGUY, 110, Deadguy04, NEUTRAL_REACTION);
end

procedure Deadguy04
begin
	gsay_reply(SCRIPT_DEADGUY, 111);
	giq_option(4, SCRIPT_DEADGUY, 112, Deadguy05, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_DEADGUY, 113, DeadguyEnd, NEUTRAL_REACTION);
end

procedure Deadguy05
begin
	if (dude_is_male) then begin
		gsay_message(SCRIPT_DEADGUY, 114, NEUTRAL_REACTION);
	end
	else begin
		gsay_message(SCRIPT_DEADGUY, 115, NEUTRAL_REACTION);
	end
end

procedure Deadguy06
begin
	if (dude_is_male) then begin
		gsay_message(SCRIPT_DEADGUY, 118, NEUTRAL_REACTION);
	end
	else begin
		gsay_message(SCRIPT_DEADGUY, 119, NEUTRAL_REACTION);
	end
end

procedure Deadguy07
begin
	if (dude_is_male) then begin
		gsay_reply(SCRIPT_DEADGUY, 122);
	end
	else begin
		gsay_reply(SCRIPT_DEADGUY, 123);
	end
	giq_option(4, SCRIPT_DEADGUY, 126, Deadguy08, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_DEADGUY, 127, combat, NEUTRAL_REACTION);
end

procedure Deadguy08
begin
	if (dude_is_male) then begin
		gsay_message(SCRIPT_DEADGUY, 128, NEUTRAL_REACTION);
	end
	else begin
		gsay_message(SCRIPT_DEADGUY, 129, NEUTRAL_REACTION);
	end
end

procedure DeadguyEnd
begin
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end