#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>

procedure start;
#include <push.h>
procedure use_p_proc;

import variable removal_ptr;


procedure start
begin
if (script_action == use_proc) then begin
    call use_p_proc;
  end
end

procedure use_p_proc
begin
  script_overrides;
  display_msg(message_str(SCRIPT_DOORCODE, 100));
  set_global_var(271, 1);
end