#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure critter_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure show_true_name;
procedure show_false_name;
procedure Dragon00;
procedure Dragon01;
procedure Dragon02;
procedure Dragon03;
procedure Dragon04;
procedure Dragon05;
procedure Dragon06;
procedure Dragon07;
procedure Dragon08;
procedure Dragon09;
procedure Dragon10;
procedure Dragon11;
procedure DragonCombat;
procedure DragonEnd;

variable hostile1;
variable initialized1;


procedure start
begin
	if (not(initialized1)) then begin
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 47);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_BLADES);
		initialized1 := 1;
	end
	else begin
		if (script_action == critter_proc) then begin
			call critter_p_proc;
		end
		else begin
			if (script_action == destroy_proc) then begin
				call destroy_p_proc;
			end
			else begin
				if (script_action == look_at_proc) then begin
					call look_at_p_proc;
				end
				else begin
					if (script_action == talk_proc) then begin
						call talk_p_proc;
					end
				end
			end
		end
	end
end

procedure critter_p_proc
begin
	if ((game_time_hour >= 700) and (game_time_hour < 1800) and (tile_num(self_obj) != 26746)) then begin
		animate_move_obj_to_tile(self_obj, 26746, ANIMATE_WALK);
	end
	else begin
		if ((game_time_hour >= 1900) or (game_time_hour < 600) and (tile_num(self_obj) != 23938)) then begin
			animate_move_obj_to_tile(self_obj, 23938, ANIMATE_WALK);
		end
	end
	if (obj_can_see_obj(self_obj, dude_obj) and (global_var(GVAR_BLADES_LEFT) < 41)) then begin
		hostile1 := 1;
	end
	if (hostile1) then begin
		hostile1 := 0;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
end

procedure destroy_p_proc
begin
	set_global_var(GVAR_BLADES_LEFT, global_var(GVAR_BLADES_LEFT) - 1);
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
end

procedure look_at_p_proc
begin
	if ((global_var(GVAR_BECOME_BLADE) == 2) or (get_critter_stat(dude_obj, 6) > 6)) then begin
		call show_true_name;
	end
	else begin
		if (get_critter_stat(dude_obj, 6) < 4) then begin
			call show_false_name;
		end
		else begin
			if (get_critter_stat(dude_obj, 4) < 5) then begin
				call show_false_name;
			end
			else begin
				if (random(0, 1)) then begin
					call show_false_name;
				end
				else begin
					call show_true_name;
				end
			end
		end
	end
end

procedure pickup_p_proc
begin
	hostile1 := 1;
end

procedure talk_p_proc
begin
	if (get_critter_stat(dude_obj, 4) < 4) then begin
		display_msg(message_str(SCRIPT_GENCHAT, 175));
	end
	else begin
		start_gdialog(SCRIPT_DRAGON, self_obj, 4, -1, -1);
		gsay_start;
		set_local_var(0, 1);
		if ((game_time_hour >= 700) and (game_time_hour < 1800)) then begin
			call Dragon00;
		end
		else begin
			if (global_var(GVAR_BECOME_BLADE) == 1) then begin
				call Dragon07;
			end
			else begin
				if (global_var(GVAR_BECOME_BLADE) == 2) then begin
					call Dragon11;
				end
				else begin
					call Dragon01;
				end
			end
		end
		gsay_end;
		end_dialogue;
	end
end

procedure show_true_name
begin
	script_overrides;
	if (local_var(0)) then begin
		display_msg(message_str(SCRIPT_DRAGON, 100));
	end
	else begin
		display_msg(message_str(SCRIPT_DRAGON, 103));
	end
end

procedure show_false_name
begin
	script_overrides;
	display_msg(message_str(SCRIPT_DRAGON, random(104, 110)));
end

procedure Dragon00
begin
	gsay_message(SCRIPT_DRAGON, 111, NEUTRAL_REACTION);
end

procedure Dragon01
begin
	gsay_reply(SCRIPT_DRAGON, 112);
	giq_option(4, SCRIPT_DRAGON, 113, Dragon02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_DRAGON, 114, Dragon06, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_DRAGON, 115, DragonCombat, NEUTRAL_REACTION);
end

procedure Dragon02
begin
	gsay_reply(SCRIPT_DRAGON, 116);
	giq_option(4, SCRIPT_DRAGON, 117, Dragon03, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_DRAGON, 118, Dragon04, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_DRAGON, 119, Dragon05, NEUTRAL_REACTION);
end

procedure Dragon03
begin
	gsay_message(SCRIPT_DRAGON, 120, NEUTRAL_REACTION);
	call DragonCombat;
end

procedure Dragon04
begin
	gsay_message(SCRIPT_DRAGON, 121, NEUTRAL_REACTION);
end

procedure Dragon05
begin
	gsay_message(SCRIPT_DRAGON, 122, NEUTRAL_REACTION);
	call DragonCombat;
end

procedure Dragon06
begin
	gsay_reply(SCRIPT_DRAGON, 123);
	giq_option(0, SCRIPT_DRAGON, 124, DragonEnd, NEUTRAL_REACTION);
	giq_option(0, SCRIPT_DRAGON, 125, DragonCombat, NEUTRAL_REACTION);
end

procedure Dragon07
begin
	gsay_reply(SCRIPT_DRAGON, 126);
	giq_option(4, SCRIPT_DRAGON, 127, DragonCombat, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_DRAGON, 128, Dragon08, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_DRAGON, 129, Dragon10, NEUTRAL_REACTION);
end

procedure Dragon08
begin
	if (obj_is_carrying_obj_pid(dude_obj, 114)) then begin
		gsay_message(SCRIPT_DRAGON, 130, NEUTRAL_REACTION);
	end
	else begin
		call Dragon09;
	end
end

procedure Dragon09
begin
	gsay_message(SCRIPT_DRAGON, 131, NEUTRAL_REACTION);
end

procedure Dragon10
begin
	gsay_message(SCRIPT_DRAGON, 132, NEUTRAL_REACTION);
end

procedure Dragon11
begin
	gsay_message(SCRIPT_DRAGON, 133, NEUTRAL_REACTION);
end

procedure DragonCombat
begin
	hostile1 := 1;
end

procedure DragonEnd
begin
end