#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure look_at_p_proc;
procedure description_p_proc;
procedure talk_p_proc;
procedure critter_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure pickup_p_proc;
procedure Dugan01;
procedure Dugan02;
procedure Dugan03;
procedure Dugan04;
procedure Dugan05;
procedure Dugan06;
procedure Dugan07;
procedure Dugan08;
procedure Dugan09;
procedure DuganEnd;

variable Initialize := 1;
variable PsstTime;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure Start
begin
	if (Initialize) then begin
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 47);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_BLADES);
		Initialize := 0;
	end
end

procedure look_at_p_proc
begin
	script_overrides;
	if (local_var(4) == 1) then begin
		display_msg(message_str(SCRIPT_DUGAN, 101));
	end
	else begin
		display_msg(message_str(SCRIPT_DUGAN, 100));
	end
end

procedure description_p_proc
begin
	script_overrides;
	if (local_var(4) == 1) then begin
		display_msg(message_str(SCRIPT_DUGAN, 101));
	end
	else begin
		display_msg(message_str(SCRIPT_DUGAN, 100));
	end
end

procedure talk_p_proc
begin
	if (global_var(GVAR_ENEMY_BLADES) == 1) then begin
		float_msg(self_obj, message_str(SCRIPT_ENEMY, random(100, 105)), FLOAT_MSG_RED);
	end
	else begin
		if ((local_var(4) == 1) and (get_critter_stat(dude_obj, 4) < 4)) then begin
			float_msg(self_obj, message_str(SCRIPT_DUGAN, 120), FLOAT_MSG_NORMAL);
		end
		else begin
			call Get_Reaction;
			start_gdialog(SCRIPT_DUGAN, self_obj, 4, -1, -1);
			gsay_start;
			call Dugan01;
			gsay_end;
			end_dialogue;
		end
	end
end

procedure critter_p_proc
begin
	if ((((game_time / 10) - PsstTime) >= 30) and (tile_distance_objs(self_obj, dude_obj) <= 10)) then begin
		float_msg(self_obj, message_str(SCRIPT_DUGAN, random(121, 125)), FLOAT_MSG_NORMAL);
		PsstTime := game_time / 10;
	end
	if (obj_can_see_obj(self_obj, dude_obj)) then begin
		if (global_var(GVAR_ENEMY_BLADES) == 1) then begin
			attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
		end
	end
end

procedure damage_p_proc
begin
	if (source_obj == dude_obj) then begin
		set_global_var(GVAR_ENEMY_BLADES, 1);
	end
end

procedure destroy_p_proc
begin
	if (source_obj == dude_obj) then begin
		set_global_var(GVAR_ENEMY_BLADES, 1);
		if (source_obj == dude_obj) then begin
			if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
				set_global_var(GVAR_BERSERKER_REPUTATION, 1);
				set_global_var(GVAR_CHAMPION_REPUTATION, 0);
			end
			if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
				set_global_var(GVAR_CHAMPION_REPUTATION, 1);
				set_global_var(GVAR_BERSERKER_REPUTATION, 0);
			end
			set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
			if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
				set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
			end
		end
	end
end

procedure pickup_p_proc
begin
	set_global_var(GVAR_ENEMY_BLADES, 1);
end

procedure Dugan01
begin
	gsay_reply(SCRIPT_DUGAN, 102);
	giq_option(4, SCRIPT_DUGAN, 103, Dugan02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_DUGAN, 104, Dugan03, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_DUGAN, 105, Dugan05, NEUTRAL_REACTION);
	if (global_var(GVAR_BLADES) < 1) then begin
		giq_option(4, SCRIPT_DUGAN, 106, Dugan08, NEUTRAL_REACTION);
	end
	giq_option(4, SCRIPT_DUGAN, 107, DuganEnd, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_DUGAN, 108, Dugan09, NEUTRAL_REACTION);
end

procedure Dugan02
begin
	gsay_message(SCRIPT_DUGAN, 109, NEUTRAL_REACTION);
end

procedure Dugan03
begin
	gsay_reply(SCRIPT_DUGAN, 110);
	call Dugan04;
end

procedure Dugan04
begin
	gsay_option(SCRIPT_DUGAN, 111, Dugan05, NEUTRAL_REACTION);
	gsay_option(SCRIPT_DUGAN, 112, Dugan06, NEUTRAL_REACTION);
	gsay_option(SCRIPT_DUGAN, 113, Dugan07, NEUTRAL_REACTION);
	gsay_option(SCRIPT_DUGAN, 114, Dugan01, NEUTRAL_REACTION);
	gsay_option(SCRIPT_DUGAN, 115, DuganEnd, NEUTRAL_REACTION);
end

procedure Dugan05
begin
	gsay_reply(SCRIPT_DUGAN, 116);
	call Dugan04;
end

procedure Dugan06
begin
	gsay_reply(SCRIPT_DUGAN, 117);
	call Dugan04;
end

procedure Dugan07
begin
	gsay_reply(SCRIPT_DUGAN, 118);
	call Dugan04;
end

procedure Dugan08
begin
	gsay_message(SCRIPT_DUGAN, 119, NEUTRAL_REACTION);
	call Dugan01;
end

procedure Dugan09
begin
	gsay_message(SCRIPT_DUGAN, 120, NEUTRAL_REACTION);
end

procedure DuganEnd
begin
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end