#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure description_p_proc;


procedure start
begin
	if (script_action == description_proc) then begin
		call description_p_proc;
	end
end

procedure description_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_FARMPART, 100));
	if (global_var(GVAR_FIX_FARM) == 1) then begin
		if (is_success(roll_vs_skill(dude_obj, 12, 0))) then begin
			display_msg(message_str(SCRIPT_FARMPART, 101));
		end
	end
end