#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure timed_event_p_proc;
procedure damage_p_proc;
procedure Farmer00;
procedure Farmer01;
procedure SendToWork;
procedure SendToSleep;
procedure CheckWorkHeading;

variable hostile1;
variable Only_Once := 1;
variable SetDayNight;
variable Sleeping;
variable LastMove;
variable destination;
variable CurrentTile;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure start
begin
	if (Only_Once) then begin
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 65);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_HUB_PEASANTS);
		Only_Once := 0;
		LastMove := 21931;
	end
	if (script_action == look_at_proc) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == pickup_proc) then begin
			call pickup_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
			else begin
				if (script_action == critter_proc) then begin
					call critter_p_proc;
				end
				else begin
					if (script_action == destroy_proc) then begin
						call destroy_p_proc;
					end
					else begin
						if (script_action == timed_event_proc) then begin
							call timed_event_p_proc;
						end
					end
				end
			end
		end
	end
end

procedure combat
begin
	hostile1 := 1;
end

procedure critter_p_proc
begin
	if (hostile1) then begin
		hostile1 := 0;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
	if (not((game_time_hour >= 1900) or (game_time_hour < 600))) then begin
		if (SetDayNight == 0) then begin
			add_timer_event(self_obj, game_ticks(30), 1);
			SetDayNight := 1;
		end
	end
	else begin
		if (Sleeping == 0) then begin
			add_timer_event(self_obj, game_ticks(2), 1);
		end
	end
	if (tile_num(self_obj) == 26724) then begin
		if (has_trait(1, self_obj, 10) != 2) then begin
			anim(self_obj, 1000, 2);
		end
	end
	call CheckWorkHeading;
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		hostile1 := 1;
	end
end

procedure talk_p_proc
begin
	call Get_Reaction;
	if ((game_time_hour >= 600) and (game_time_hour < 700) or ((game_time_hour >= 700) and (game_time_hour < 1800))) then begin
		call Farmer00;
	end
	else begin
		call Farmer01;
	end
end

procedure destroy_p_proc
begin
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_FEMFARMR, 100));
end

procedure timed_event_p_proc
begin
	if ((game_time_hour >= 600) and (game_time_hour < 700) or ((game_time_hour >= 700) and (game_time_hour < 1800))) then begin
		Sleeping := 0;
		call SendToWork;
	end
	else begin
		call SendToSleep;
	end
end

procedure damage_p_proc
begin
	variable LVar0 := 0;
	LVar0 := obj_pid(source_obj);
	if (party_member_obj(LVar0) != 0) then begin
		set_global_var(GVAR_ENEMY_HUB, 1);
	end
end

procedure Farmer00
begin
	variable LVar0 := 0;
	LVar0 := random(1, 5);
	if (LVar0 == 1) then begin
		float_msg(self_obj, message_str(SCRIPT_FEMFARMR, 101), FLOAT_MSG_RED);
	end
	else begin
		if (LVar0 == 2) then begin
			if ((game_time_hour >= 600) and (game_time_hour < 1200)) then begin
				float_msg(self_obj, message_str(SCRIPT_FEMFARMR, 102), FLOAT_MSG_RED);
			end
			else begin
				if ((game_time_hour >= 1200) and (game_time_hour < 1600)) then begin
					float_msg(self_obj, message_str(SCRIPT_FEMFARMR, 103), FLOAT_MSG_RED);
				end
				else begin
					float_msg(self_obj, message_str(SCRIPT_FEMFARMR, 104), FLOAT_MSG_RED);
				end
			end
		end
		else begin
			if (LVar0 == 3) then begin
				float_msg(self_obj, message_str(SCRIPT_FEMFARMR, 105), FLOAT_MSG_RED);
			end
			else begin
				if (LVar0 == 4) then begin
					float_msg(self_obj, message_str(SCRIPT_FEMFARMR, 106), FLOAT_MSG_RED);
				end
				else begin
					if (LVar0 == 5) then begin
						float_msg(self_obj, message_str(SCRIPT_FEMFARMR, 107), FLOAT_MSG_RED);
					end
					else begin
						float_msg(self_obj, message_str(SCRIPT_FEMFARMR, 108), FLOAT_MSG_RED);
					end
				end
			end
		end
	end
end

procedure Farmer01
begin
	float_msg(self_obj, message_str(SCRIPT_FEMFARMR, random(109, 116)), FLOAT_MSG_RED);
end

procedure SendToWork
begin
	destination := 0;
	while(destination == 0) do begin
		destination := random(1, 9);
		if (destination == 1) then begin
			destination := 21931;
		end
		else begin
			if (destination == 2) then begin
				destination := 23330;
			end
			else begin
				if (destination == 3) then begin
					destination := 20934;
				end
				else begin
					if (destination == 4) then begin
						destination := 23134;
					end
					else begin
						if (destination == 5) then begin
							destination := 21538;
						end
						else begin
							if (destination == 6) then begin
								destination := 20542;
							end
							else begin
								if (destination == 7) then begin
									destination := 23342;
								end
								else begin
									if (destination == 8) then begin
										destination := 22150;
									end
									else begin
										if (destination == 9) then begin
											destination := 23146;
										end
									end
								end
							end
						end
					end
				end
			end
		end
		if (destination == LastMove) then begin
			destination := 0;
		end
	end
	LastMove := destination;
	reg_anim_func(2, self_obj);
	reg_anim_func(1, 1);
	reg_anim_obj_move_to_tile(self_obj, destination, -1);
	reg_anim_func(3, 0);
	add_timer_event(self_obj, game_ticks(random(10, 30)), 1);
end

procedure SendToSleep
begin
	if (Sleeping == 0) then begin
		reg_anim_func(2, self_obj);
		reg_anim_func(1, 1);
		reg_anim_obj_move_to_tile(self_obj, 26724, -1);
		reg_anim_func(3, 0);
		Sleeping := 1;
		SetDayNight := 0;
		LastMove := 26724;
	end
end

procedure CheckWorkHeading
begin
	if (Sleeping == 0) then begin
		CurrentTile := tile_num(self_obj);
		if (CurrentTile == LastMove) then begin
			if (has_trait(1, self_obj, 10) != 0) then begin
				anim(self_obj, 1000, 0);
			end
		end
	end
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end