#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure destroy_p_proc;
procedure critter_p_proc;

variable start_init;
variable hostile1;


procedure start
begin
	variable LVar0 := 0;
	if (not(start_init) and metarule(14, 0)) then begin
		LVar0 := obj_pid(self_obj);
		if (LVar0 == 16777261) then begin
			critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_FLOATER);
			critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 43);
		end
		else begin
			if (LVar0 == 16777259) then begin
				critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_CENTAUR);
				critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 43);
			end
		end
		start_init := 1;
	end
	else begin
		if (script_action == destroy_proc) then begin
			call destroy_p_proc;
		end
		else begin
			if (script_action == critter_proc) then begin
				call critter_p_proc;
			end
		end
	end
end

procedure destroy_p_proc
begin
	if (source_obj == dude_obj) then begin
		if (source_obj == dude_obj) then begin
			if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
				set_global_var(GVAR_BERSERKER_REPUTATION, 1);
				set_global_var(GVAR_CHAMPION_REPUTATION, 0);
			end
			if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
				set_global_var(GVAR_CHAMPION_REPUTATION, 1);
				set_global_var(GVAR_BERSERKER_REPUTATION, 0);
			end
			set_global_var(GVAR_BAD_MONSTER, global_var(GVAR_BAD_MONSTER) + 1);
			if ((global_var(GVAR_BAD_MONSTER) % 6) == 0) then begin
				set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 1);
			end
		end
	end
end

procedure critter_p_proc
begin
	if (not(hostile1)) then begin
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
		hostile1 := 1;
	end
end