#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure damage_p_proc;
procedure combat_p_proc;
procedure look_at_p_proc;
procedure Cop00;
procedure Cop01;
procedure Cop02;

variable hostile1;
variable Only_Once := 1;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure start
begin
	if (Only_Once) then begin
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 40);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_HUB_POLICE);
	end
	if (script_action == look_at_proc) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == pickup_proc) then begin
			call pickup_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
			else begin
				if (script_action == critter_proc) then begin
					call critter_p_proc;
				end
				else begin
					if (script_action == destroy_proc) then begin
						call destroy_p_proc;
					end
				end
			end
		end
	end
end

procedure combat
begin
	hostile1 := 1;
end

procedure critter_p_proc
begin
	if (hostile1) then begin
		hostile1 := 0;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
	if (global_var(GVAR_ENEMY_HUB) == 1) then begin
		hostile1 := 1;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		hostile1 := 1;
	end
end

procedure talk_p_proc
begin
	call Get_Reaction;
	if (cur_map_index == MAP_HUBENT) then begin
		call Cop01;
	end
	else begin
		if (cur_map_index == MAP_HUBDWNTN) then begin
			call Cop00;
		end
		else begin
			call Cop02;
		end
	end
end

procedure destroy_p_proc
begin
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
end

procedure damage_p_proc
begin
	variable LVar0 := 0;
	LVar0 := obj_pid(source_obj);
	if (party_member_obj(LVar0) != 0) then begin
		set_global_var(GVAR_ENEMY_HUB, 1);
	end
end

procedure combat_p_proc
begin
	if (global_var(GVAR_ENEMY_HUB) == 1) then begin
		hostile1 := 1;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_GENCOP, 100));
end

procedure Cop00
begin
	if (random(0, 3) == 1) then begin
		float_msg(self_obj, message_str(SCRIPT_GENCOP, random(101, 106)), FLOAT_MSG_RED);
	end
	else begin
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			float_msg(self_obj, message_str(SCRIPT_GENCOP, random(113, 116)), FLOAT_MSG_RED);
		end
		else begin
			if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
				if (dude_is_male) then begin
					float_msg(self_obj, message_str(SCRIPT_GENCOP, random(110, 112)), FLOAT_MSG_RED);
				end
				else begin
					float_msg(self_obj, message_str(SCRIPT_GENCOP, random(110, 111)), FLOAT_MSG_RED);
				end
			end
			else begin
				if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
					float_msg(self_obj, message_str(SCRIPT_GENCOP, random(117, 118)), FLOAT_MSG_RED);
				end
				else begin
					if ((obj_item_subtype(critter_inven_obj(dude_obj, 1)) == 3) or (obj_item_subtype(critter_inven_obj(dude_obj, 2)) == 3)) then begin
						float_msg(self_obj, message_str(SCRIPT_GENCOP, random(107, 109)), FLOAT_MSG_RED);
					end
					else begin
						if (global_var(GVAR_DEATHCLAW_SEED) == 2) then begin
							float_msg(self_obj, message_str(SCRIPT_GENCOP, 119), FLOAT_MSG_RED);
						end
						else begin
							float_msg(self_obj, message_str(SCRIPT_GENCOP, random(101, 106)), FLOAT_MSG_RED);
						end
					end
				end
			end
		end
	end
end

procedure Cop01
begin
	if (random(0, 3) == 1) then begin
		float_msg(self_obj, message_str(SCRIPT_GENCOP, random(120, 129)), FLOAT_MSG_RED);
	end
	else begin
		if ((obj_item_subtype(critter_inven_obj(dude_obj, 1)) == 3) or (obj_item_subtype(critter_inven_obj(dude_obj, 2)) == 3)) then begin
			float_msg(self_obj, message_str(SCRIPT_GENCOP, random(130, 133)), FLOAT_MSG_RED);
		end
		else begin
			if (obj_pid(critter_inven_obj(dude_obj, 0)) == 3) then begin
				float_msg(self_obj, message_str(SCRIPT_GENCOP, 134), FLOAT_MSG_RED);
			end
			else begin
				if (global_var(GVAR_PC_WANTED) == 1) then begin
					float_msg(self_obj, message_str(SCRIPT_GENCOP, random(135, 137)), FLOAT_MSG_RED);
				end
				else begin
					if (global_var(GVAR_FARGO_TRADERS_STATUS) == 1) then begin
						float_msg(self_obj, message_str(SCRIPT_GENCOP, 138), FLOAT_MSG_RED);
					end
					else begin
						if (global_var(GVAR_WATER_MERCHANTS_STATUS) == 1) then begin
							float_msg(self_obj, message_str(SCRIPT_GENCOP, 139), FLOAT_MSG_RED);
						end
						else begin
							if (global_var(GVAR_CRIMSON_CARAVANS_STATUS) == 1) then begin
								float_msg(self_obj, message_str(SCRIPT_GENCOP, 140), FLOAT_MSG_RED);
							end
							else begin
								if (global_var(GVAR_UNDERGROUND_STATUS) == 1) then begin
									float_msg(self_obj, message_str(SCRIPT_GENCOP, random(141, 143)), FLOAT_MSG_RED);
								end
								else begin
									float_msg(self_obj, message_str(SCRIPT_GENCOP, random(120, 129)), FLOAT_MSG_RED);
								end
							end
						end
					end
				end
			end
		end
	end
end

procedure Cop02
begin
	if (random(0, 3) == 1) then begin
		float_msg(self_obj, message_str(SCRIPT_GENCOP, 144), FLOAT_MSG_RED);
	end
	else begin
		if (global_var(GVAR_PC_WANTED) == 1) then begin
			float_msg(self_obj, message_str(SCRIPT_GENCOP, random(155, 157)), FLOAT_MSG_RED);
		end
		else begin
			if (global_var(GVAR_FARGO_TRADERS_STATUS) == 1) then begin
				float_msg(self_obj, message_str(SCRIPT_GENCOP, 158), FLOAT_MSG_RED);
			end
			else begin
				if (global_var(GVAR_WATER_MERCHANTS_STATUS) == 1) then begin
					float_msg(self_obj, message_str(SCRIPT_GENCOP, 159), FLOAT_MSG_RED);
				end
				else begin
					if (global_var(GVAR_CRIMSON_CARAVANS_STATUS) == 1) then begin
						float_msg(self_obj, message_str(SCRIPT_GENCOP, 160), FLOAT_MSG_RED);
					end
					else begin
						if (global_var(GVAR_UNDERGROUND_STATUS) == 1) then begin
							float_msg(self_obj, message_str(SCRIPT_GENCOP, random(161, 163)), FLOAT_MSG_RED);
						end
						else begin
							float_msg(self_obj, message_str(SCRIPT_GENCOP, random(144, 154)), FLOAT_MSG_RED);
						end
					end
				end
			end
		end
	end
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end