#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure do_dialogue;
procedure sys_dialog;
procedure guard00;
procedure guard01;
procedure guard02;
procedure guard03;
procedure guard04;
procedure guard05;
procedure guard06;
procedure guard07;
procedure guard07a;
procedure guard07b;
procedure guard08;
procedure guard09;
procedure guard10;
procedure guard11;
procedure guard12;
procedure guard13;
procedure guard14;
procedure guard15;
procedure guardend;
procedure combat;
procedure weapon_check;
procedure Critter_Action;
procedure damage_p_proc;

import variable killing_women;

variable HOSTILE;
variable only_once := 1;
variable Weapons;
variable rndx;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;

procedure first;
procedure notfirst;


procedure start
begin
	if (only_once) then begin
		only_once := 0;
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 6);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_GENERIC_RAIDER);
	end
	if (script_action == timed_event_proc) then begin
		if (fixed_param == 1) then begin
			if ((obj_item_subtype(critter_inven_obj(dude_obj, 1)) == 3) or (obj_item_subtype(critter_inven_obj(dude_obj, 2)) == 3)) then begin
				call combat;
			end
		end
		else begin
			if (fixed_param == 2) then begin
				if (tile_distance_objs(self_obj, dude_obj) < 6) then begin
					call combat;
				end
			end
			else begin
				if (fixed_param == 3) then begin
					if (tile_distance_objs(self_obj, dude_obj) < 8) then begin
						call combat;
					end
				end
			end
		end
	end
	else begin
		if (script_action == talk_proc) then begin
			if (local_var(5) == 1) then begin
				display_msg(message_str(SCRIPT_GENRAID2, 100));
			end
			else begin
				call do_dialogue;
			end
		end
		else begin
			if (script_action == pickup_proc) then begin
				HOSTILE := 1;
			end
		end
	end
	if (script_action == critter_proc) then begin
		call Critter_Action;
		if (HOSTILE) then begin
			HOSTILE := 0;
			attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
		end
		else begin
			if (obj_can_see_obj(self_obj, dude_obj) and (global_var(GVAR_GARLS_FRIEND) != 1)) then begin
				if ((obj_item_subtype(critter_inven_obj(dude_obj, 1)) == 3) or (obj_item_subtype(critter_inven_obj(dude_obj, 2)) == 3) and ((Weapons == 0) and (killing_women == 0))) then begin
					Weapons := 1;
					dialogue_system_enter;
				end
			end
		end
	end
	else begin
		if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
			script_overrides;
			display_msg(message_str(SCRIPT_GENRAID2, 101));
		end
		else begin
			if (script_action == damage_proc) then begin
				call damage_p_proc;
			end
			else begin
				if (script_action == destroy_proc) then begin
					if (source_obj == dude_obj) then begin
						if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
							set_global_var(GVAR_BERSERKER_REPUTATION, 1);
							set_global_var(GVAR_CHAMPION_REPUTATION, 0);
						end
						if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
							set_global_var(GVAR_CHAMPION_REPUTATION, 1);
							set_global_var(GVAR_BERSERKER_REPUTATION, 0);
						end
						set_global_var(GVAR_BAD_MONSTER, global_var(GVAR_BAD_MONSTER) + 1);
						if ((global_var(GVAR_BAD_MONSTER) % 6) == 0) then begin
							set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 1);
						end
					end
					set_global_var(GVAR_ENEMY_RAIDERS, 1);
					set_global_var(GVAR_GARLS_FRIEND, 0);
					set_global_var(GVAR_TOTAL_RAIDERS, global_var(GVAR_TOTAL_RAIDERS) - 1);
				end
			end
		end
	end
end

procedure do_dialogue
begin
	if (global_var(GVAR_MISTAKEN_ID) == 1) then begin
		call guard00;
	end
	else begin
		if ((Weapons == 1) and (killing_women == 0) and (global_var(GVAR_GARLS_FRIEND) != 1)) then begin
			call guard02;
		end
		else begin
			call sys_dialog;
		end
	end
end

procedure sys_dialog
begin
	set_local_var(3, 1);
	call Get_Reaction;
	start_gdialog(SCRIPT_GENRAID2, self_obj, 4, -1, -1);
	gsay_start;
	if (local_var(4) == 0) then begin
		set_local_var(4, 1);
		call guard04;
	end
	else begin
		call guard15;
	end
	gsay_end;
	end_dialogue;
end

procedure guard00
begin
	float_msg(self_obj, message_str(SCRIPT_GENRAID2, random(102, 106)), FLOAT_MSG_YELLOW);
end

procedure guard01
begin
	rndx := random(1, 5);
	if (rndx == 1) then begin
		gsay_message(SCRIPT_GENRAID2, 107, NEUTRAL_REACTION);
	end
	else begin
		if (rndx == 2) then begin
			gsay_message(SCRIPT_GENRAID2, 108, NEUTRAL_REACTION);
		end
		else begin
			if (rndx == 3) then begin
				gsay_message(SCRIPT_GENRAID2, 109, NEUTRAL_REACTION);
			end
			else begin
				if (rndx == 4) then begin
					gsay_message(SCRIPT_GENRAID2, 110, NEUTRAL_REACTION);
				end
				else begin
					if (rndx == 5) then begin
						gsay_message(SCRIPT_GENRAID2, 111, NEUTRAL_REACTION);
					end
				end
			end
		end
	end
end

procedure guard02
begin
	float_msg(self_obj, message_str(SCRIPT_GENRAID2, random(112, 115)), FLOAT_MSG_YELLOW);
	add_timer_event(self_obj, game_ticks(9), 1);
end

procedure guard03
begin
	rndx := random(1, 3);
	if (rndx == 1) then begin
		gsay_message(SCRIPT_GENRAID2, 116, NEUTRAL_REACTION);
	end
	else begin
		if (rndx == 2) then begin
			gsay_message(SCRIPT_GENRAID2, 117, NEUTRAL_REACTION);
		end
		else begin
			if (rndx == 3) then begin
				gsay_message(SCRIPT_GENRAID2, 118, NEUTRAL_REACTION);
			end
		end
	end
	add_timer_event(self_obj, game_ticks(10), 2);
end

procedure guard04
begin
	gsay_reply(SCRIPT_GENRAID2, 119);
	if ((global_var(GVAR_RESCUE_TANDI) == 1) and (global_var(GVAR_TALKED_ABOUT_TANDI) == 1)) then begin
		giq_option(4, SCRIPT_GENRAID2, 120, guard07, NEUTRAL_REACTION);
	end
	giq_option(4, SCRIPT_GENRAID2, 121, guard06, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_GENRAID2, 122, guard05, NEUTRAL_REACTION);
end

procedure guard05
begin
	gsay_message(SCRIPT_GENRAID2, 123, NEUTRAL_REACTION);
end

procedure guard06
begin
	gsay_message(SCRIPT_GENRAID2, 124, NEUTRAL_REACTION);
	call Down_React;
end

procedure guard07
begin
	gsay_reply(SCRIPT_GENRAID2, 125);
	giq_option(4, SCRIPT_GENRAID2, 126, guard08, NEUTRAL_REACTION);
	giq_option(6, SCRIPT_GENRAID2, 127, guard07a, NEUTRAL_REACTION);
	if (is_success(do_check(dude_obj, 1, 0))) then begin
		giq_option(4, SCRIPT_GENRAID2, 128, guard07b, NEUTRAL_REACTION);
	end
end

procedure guard07a
begin
	if (is_success(roll_vs_skill(dude_obj, 14, 0))) then begin
		call guard09;
	end
	else begin
		call guard11;
	end
end

procedure guard07b
begin
	if (is_success(roll_vs_skill(dude_obj, 14, -20))) then begin
		call guard12;
	end
	else begin
		call guard13;
	end
end

procedure guard08
begin
	gsay_message(SCRIPT_GENRAID2, 129, NEUTRAL_REACTION);
end

procedure guard09
begin
	gsay_reply(SCRIPT_GENRAID2, 130);
	giq_option(6, SCRIPT_GENRAID2, 131, guard10, NEUTRAL_REACTION);
end

procedure guard10
begin
	gsay_message(SCRIPT_GENRAID2, 132, NEUTRAL_REACTION);
end

procedure guard11
begin
	gsay_message(SCRIPT_GENRAID2, 133, NEUTRAL_REACTION);
end

procedure guard12
begin
	gsay_message(SCRIPT_GENRAID2, 134, NEUTRAL_REACTION);
	set_local_var(5, 1);
end

procedure guard13
begin
	gsay_message(SCRIPT_GENRAID2, 135, NEUTRAL_REACTION);
	call combat;
end

procedure guard14
begin
	gsay_message(SCRIPT_GENRAID2, 136, NEUTRAL_REACTION);
	add_timer_event(self_obj, game_ticks(12), 3);
end

procedure guard15
begin
	gsay_message(SCRIPT_GENRAID2, 137, NEUTRAL_REACTION);
end

procedure guardend
begin
end

procedure combat
begin
	if (global_var(GVAR_MISTAKEN_ID) == 1) then begin
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 87);
	end
	HOSTILE := 1;
end

procedure weapon_check
begin
	if ((obj_item_subtype(critter_inven_obj(dude_obj, 1)) == 3) or (obj_item_subtype(critter_inven_obj(dude_obj, 2)) == 3)) then begin
		Weapons := 0;
	end
	else begin
		Weapons := 1;
	end
end

procedure Critter_Action
begin
	variable LVar0 := 0;
	if (global_var(GVAR_TANDI_STATUS) == 2) then begin
		set_global_var(GVAR_ENEMY_RAIDERS, 1);
	end
	else begin
		if (global_var(GVAR_MISTAKEN_ID)) then begin
			set_global_var(GVAR_ENEMY_RAIDERS, 0);
			if (tile_distance_objs(self_obj, dude_obj) < 3) then begin
				LVar0 := tile_num_in_direction(tile_num(self_obj), random(0, 5), 3);
				if (tile_distance(tile_num(self_obj), LVar0) > 2) then begin
					if (random(0, 9) == 0) then begin
						float_msg(self_obj, message_str(SCRIPT_GENRAIDR, random(102, 106)), FLOAT_MSG_YELLOW);
					end
					animate_move_obj_to_tile(self_obj, LVar0, ANIMATE_WALK);
				end
			end
		end
		else begin
			if (global_var(GVAR_TANDI_ESCAPE)) then begin
				set_global_var(GVAR_ENEMY_RAIDERS, 1);
			end
			if (obj_can_see_obj(self_obj, dude_obj)) then begin
				if (global_var(GVAR_RAID_LOOTING)) then begin
					set_global_var(GVAR_ENEMY_RAIDERS, 1);
				end
			end
			if (map_var(2) == 1) then begin
				set_global_var(GVAR_ENEMY_RAIDERS, 1);
			end
		end
	end
	if (global_var(GVAR_ENEMY_RAIDERS) and obj_can_see_obj(self_obj, dude_obj)) then begin
		HOSTILE := 1;
	end
	if (tile_distance_objs(self_obj, dude_obj) > 12) then begin
		HOSTILE := 0;
	end
end

procedure damage_p_proc
begin
	if (global_var(GVAR_MISTAKEN_ID) == 0) then begin
		set_global_var(GVAR_ENEMY_RAIDERS, 1);
	end
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end

procedure first
begin
end

procedure notfirst
begin
end