#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure appear;


procedure start
begin
	if (script_action != MAP_VAULT13) then begin
		if (global_var(GVAR_NECROPOLIS_INVADED) == 1) then begin
			call appear;
		end
		else begin
			script_overrides;
			set_obj_visibility(self_obj, 1);
		end
	end
end

procedure appear
begin
	set_obj_visibility(self_obj, 0);
end