#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure do_dialogue;
procedure ghoulend;
procedure ghoulcbt;
procedure ghoul00;
procedure ghoul01;
procedure ghoul01a;
procedure ghoul02;
procedure ghoul03;
procedure ghoul03a;
procedure ghoul04;
procedure ghoul05;
procedure ghoul06;
procedure Critter_Action;
procedure timetomove;

variable Hostile;
variable init;
variable maxleash := 9;
variable noevent;
variable loopcount;
variable new_tile;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure start
begin
	if (not(init)) then begin
		if (local_var(7) == 0) then begin
			set_local_var(7, tile_num(self_obj));
			set_local_var(5, 0);
		end
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 30);
		init := 1;
	end
	if (script_action == talk_proc) then begin
		call do_dialogue;
	end
	else begin
		if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
			script_overrides;
			display_msg(message_str(SCRIPT_GHGUARD, 100));
		end
		else begin
			if (script_action == pickup_proc) then begin
				Hostile := 1;
			end
			else begin
				if (script_action == critter_proc) then begin
					call Critter_Action;
				end
				else begin
					if (script_action == destroy_proc) then begin
						if (source_obj == dude_obj) then begin
							if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
								set_global_var(GVAR_BERSERKER_REPUTATION, 1);
								set_global_var(GVAR_CHAMPION_REPUTATION, 0);
							end
							if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
								set_global_var(GVAR_CHAMPION_REPUTATION, 1);
								set_global_var(GVAR_BERSERKER_REPUTATION, 0);
							end
							set_global_var(GVAR_BAD_MONSTER, global_var(GVAR_BAD_MONSTER) + 1);
							if ((global_var(GVAR_BAD_MONSTER) % 6) == 0) then begin
								set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 1);
							end
						end
					end
				end
			end
		end
	end
end

procedure do_dialogue
begin
	start_gdialog(SCRIPT_GHGUARD, self_obj, 4, -1, -1);
	gsay_start;
	if (local_var(4)) then begin
		call ghoul06;
	end
	else begin
		if (local_var(1) >= 2) then begin
			set_local_var(4, 1);
			call ghoul01;
		end
		else begin
			set_local_var(4, 1);
			call ghoul00;
		end
	end
	gsay_end;
	end_dialogue;
end

procedure ghoulend
begin
end

procedure ghoulcbt
begin
	Hostile := 1;
end

procedure ghoul00
begin
	gsay_message(SCRIPT_GHGUARD, 101, NEUTRAL_REACTION);
	call ghoulcbt;
end

procedure ghoul01
begin
	gsay_reply(SCRIPT_GHGUARD, 102);
	giq_option(6, SCRIPT_GHGUARD, 103, ghoul01a, NEUTRAL_REACTION);
	giq_option(3, SCRIPT_GHGUARD, 104, ghoulend, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_GHGUARD, 105, ghoul00, NEUTRAL_REACTION);
end

procedure ghoul01a
begin
	if (is_success(roll_vs_skill(dude_obj, 14, 0))) then begin
		call ghoul02;
	end
	else begin
		call ghoul03;
	end
end

procedure ghoul02
begin
	gsay_reply(SCRIPT_GHGUARD, 106);
	giq_option(3, SCRIPT_GHGUARD, 107, ghoulcbt, NEUTRAL_REACTION);
	giq_option(5, SCRIPT_GHGUARD, 108, ghoulend, NEUTRAL_REACTION);
end

procedure ghoul03
begin
	gsay_reply(SCRIPT_GHGUARD, 109);
	giq_option(3, SCRIPT_GHGUARD, 110, ghoul03a, NEUTRAL_REACTION);
	giq_option(3, SCRIPT_GHGUARD, 111, ghoul04, NEUTRAL_REACTION);
end

procedure ghoul03a
begin
	if (is_success(roll_vs_skill(dude_obj, 14, 0))) then begin
		call ghoul05;
	end
	else begin
		call ghoul04;
	end
end

procedure ghoul04
begin
	gsay_message(SCRIPT_GHGUARD, 112, NEUTRAL_REACTION);
	call ghoulend;
end

procedure ghoul05
begin
	gsay_reply(SCRIPT_GHGUARD, 113);
	giq_option(4, SCRIPT_GHGUARD, 114, ghoulend, NEUTRAL_REACTION);
end

procedure ghoul06
begin
	gsay_message(SCRIPT_GHGUARD, 115, NEUTRAL_REACTION);
	call ghoulend;
end

procedure Critter_Action
begin
	if (Hostile > 0) then begin
		Hostile := 0;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
	else begin
		if (local_var(5)) then begin
			loopcount := loopcount + 1;
			if (loopcount > 40) then begin
				loopcount := 0;
				if (noevent == 0) then begin
					noevent := 1;
					add_timer_event(self_obj, game_ticks(random(5, 13)), 0);
				end
			end
		end
	end
end

procedure timetomove
begin
	noevent := 0;
	set_local_var(6, tile_num(self_obj));
	new_tile := tile_num_in_direction(local_var(6), random(0, 5), 2);
	if (tile_distance(local_var(7), new_tile) < maxleash) then begin
		animate_move_obj_to_tile(self_obj, new_tile, ANIMATE_WALK);
	end
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end