#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>


procedure start
begin
	if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
		script_overrides;
		display_msg(message_str(SCRIPT_GLOCABN, 100));
	end
	else begin
		if (script_action == pickup_proc) then begin
			if (local_var(0) == 0) then begin
				script_overrides;
				display_msg(message_str(SCRIPT_GLOCABN, 101));
			end
		end
		else begin
			if (script_action == use_skill_on_proc) then begin
				if (action_being_used == 9) then begin
					if (is_success(roll_vs_skill(dude_obj, 9, -15))) then begin
						set_local_var(0, 1);
						display_msg(message_str(SCRIPT_GLOCABN, 102));
					end
					else begin
						display_msg(message_str(SCRIPT_GLOCABN, 103));
					end
				end
				else begin
					if (action_being_used == 12) then begin
						if (is_success(roll_vs_skill(dude_obj, 12, -5))) then begin
							set_local_var(0, 1);
							display_msg(message_str(SCRIPT_GLOCABN, 104));
						end
						else begin
							display_msg(message_str(SCRIPT_GLOCABN, 105));
						end
					end
					else begin
						display_msg(message_str(SCRIPT_GLOCABN, 106));
					end
				end
			end
		end
	end
end