#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>


procedure start
begin
	variable LVar0 := 0;
	if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
		script_overrides;
		LVar0 := random(1, 4);
		if (LVar0 == 1) then begin
			display_msg(message_str(SCRIPT_GLOCOMP, 100));
		end
		else begin
			if (LVar0 == 2) then begin
				display_msg(message_str(SCRIPT_GLOCOMP, 101));
			end
			else begin
				if (LVar0 == 3) then begin
					display_msg(message_str(SCRIPT_GLOCOMP, 102));
				end
				else begin
					if (LVar0 == 4) then begin
						display_msg(message_str(SCRIPT_GLOCOMP, 103));
					end
				end
			end
		end
	end
end