#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>


procedure start
begin
	if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
		script_overrides;
		display_msg(message_str(SCRIPT_GLWBOX, 100));
	end
	else begin
		if (script_action == use_obj_on_proc) then begin
			if (obj_being_used_with == 84) then begin
				if (is_success(roll_vs_skill(dude_obj, 9, 0))) then begin
					set_local_var(0, 1);
					display_msg(message_str(SCRIPT_GLWBOX, 101));
				end
				else begin
					display_msg(message_str(SCRIPT_GLWBOX, 102));
				end
			end
			else begin
				display_msg(message_str(SCRIPT_GLWBOX, 103));
			end
		end
		else begin
			if (script_action == use_proc) then begin
				if (local_var(0) == 0) then begin
					script_overrides;
					display_msg(message_str(SCRIPT_GLWBOX, 104));
				end
			end
			else begin
				if (script_action == use_skill_on_proc) then begin
					script_overrides;
					if (action_being_used == 9) then begin
						if (is_success(roll_vs_skill(dude_obj, 9, -15))) then begin
							set_local_var(0, 1);
							display_msg(message_str(SCRIPT_GLWBOX, 105));
						end
						else begin
							display_msg(message_str(SCRIPT_GLWBOX, 106));
						end
					end
					else begin
						display_msg(message_str(SCRIPT_GLWBOX, 107));
					end
				end
			end
		end
	end
end