#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>

variable HEREBEFORE;


procedure start
begin
	if (script_action == spatial_proc) then begin
		if (obj_type(source_obj) == dude_obj) then begin
			if (not(HEREBEFORE)) then begin
				HEREBEFORE := 1;
				display_msg(message_str(SCRIPT_GRAFFITI, 100));
			end
		end
	end
end