#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure do_dialogue;

variable in_combat;
variable rndx;
variable rndy;
variable new_obj;
variable new_obj_picked;
variable my_tile;
variable scared;


procedure start
begin
	variable LVar0 := 0;
	variable LVar1 := 0;
	variable LVar2 := 0;
	variable LVar3 := 0;
	variable LVar4 := 0;
	if (script_action == talk_proc) then begin
		call do_dialogue;
	end
end

procedure do_dialogue
begin
	start_gdialog(SCRIPT_GUARD, self_obj, 4, -1, -1);
	rndx := random(0, 6);
	if (rndx == 0) then begin
		sayMessage(0, message_str(SCRIPT_GUARD, 102));
	end
	if (rndx == 1) then begin
		sayMessage(0, message_str(SCRIPT_GUARD, 103));
	end
	if (rndx == 2) then begin
		sayMessage(0, message_str(SCRIPT_GUARD, 104));
	end
	if (rndx == 3) then begin
		sayMessage(0, message_str(SCRIPT_GUARD, 105));
	end
	if (rndx == 4) then begin
		sayMessage(0, message_str(SCRIPT_GUARD, 106));
	end
	if (rndx == 5) then begin
		sayMessage(0, message_str(SCRIPT_GUARD, 107));
	end
	if (rndx == 6) then begin
		sayMessage(0, message_str(SCRIPT_GUARD, 108));
	end
	end_dialogue;
end