#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure use_p_proc;


procedure start
begin
	if (script_action == use_proc) then begin
		call use_p_proc;
	end
end

procedure use_p_proc
begin
	if (map_var(52) == 0) then begin
		move_to(dude_obj, 25539, 0);
	end
	else begin
		display_msg(message_str(SCRIPT_HDTDN2UP, 100));
	end
end