#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure damage_p_proc;
procedure combat_p_proc;
procedure Daren01;
procedure Daren02;
procedure Daren03;
procedure Daren04;
procedure Daren05;
procedure Daren05a;
procedure Daren06;
procedure Daren07;
procedure DarenCombat;
procedure DarenEndLeon;

variable hostile1;
variable Only_Once := 1;
variable visible := 1;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure start
begin
	if (Only_Once) then begin
		Only_Once := 0;
		if (global_var(GVAR_KILL_MERCHANT) == 5) then begin
			set_obj_visibility(self_obj, 1);
			visible := 0;
		end
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 42);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_LOSER);
	end
	if (script_action == look_at_proc) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == pickup_proc) then begin
			call pickup_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
			else begin
				if (script_action == critter_proc) then begin
					call critter_p_proc;
				end
				else begin
					if (script_action == destroy_proc) then begin
						call destroy_p_proc;
					end
					else begin
						if (script_action == damage_proc) then begin
							call damage_p_proc;
						end
						else begin
							if (script_action == combat_proc) then begin
								call combat_p_proc;
							end
						end
					end
				end
			end
		end
	end
end

procedure combat
begin
	hostile1 := 1;
end

procedure critter_p_proc
begin
	if (visible == 0) then begin
		script_overrides;
	end
	else begin
		if (hostile1) then begin
			hostile1 := 0;
			attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
		end
		if (map_var(5) == 1) then begin
			if ((obj_can_hear_obj(self_obj, dude_obj) == 1) or (obj_can_see_obj(self_obj, dude_obj) == 1)) then begin
				call combat;
			end
		end
		else begin
			if ((game_time_hour >= 600) and (game_time_hour < 700) or ((game_time_hour >= 700) and (game_time_hour < 1800))) then begin
				if (tile_num(self_obj) != 25125) then begin
					animate_move_obj_to_tile(self_obj, 25125, ANIMATE_WALK);
				end
				else begin
					if ((tile_num(dude_obj) == 24522) and (map_var(1) == 0)) then begin
						dialogue_system_enter;
					end
				end
			end
			else begin
				if (tile_num(self_obj) != 24708) then begin
					animate_move_obj_to_tile(self_obj, 24708, ANIMATE_WALK);
				end
			end
		end
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		hostile1 := 1;
	end
end

procedure talk_p_proc
begin
	call Get_Reaction;
	if ((game_time_hour >= 1900) or (game_time_hour < 600)) then begin
		float_msg(self_obj, message_str(SCRIPT_HIGHTOWR, 127), FLOAT_MSG_RED);
		call combat;
	end
	else begin
		if (global_var(GVAR_ENEMY_HUB) == 1) then begin
			float_msg(self_obj, message_str(SCRIPT_HIGHTOWR, 127), FLOAT_MSG_RED);
			call combat;
		end
		else begin
			if (local_var(4) == 0) then begin
				set_local_var(4, 1);
				start_gdialog(SCRIPT_HIGHTOWR, self_obj, 4, -1, -1);
				gsay_start;
				call Daren01;
				gsay_end;
				end_dialogue;
			end
			else begin
				float_msg(self_obj, message_str(SCRIPT_HIGHTOWR, 127), FLOAT_MSG_RED);
				call combat;
			end
		end
	end
end

procedure destroy_p_proc
begin
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
	set_map_var(0, map_var(0) + 1);
	if (map_var(0) > 1) then begin
		set_global_var(GVAR_KILL_MERCHANT, 2);
	end
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_HIGHTOWR, 100));
end

procedure damage_p_proc
begin
	set_map_var(5, 1);
	set_global_var(GVAR_KILL_MERCHANT, 5);
end

procedure combat_p_proc
begin
	critter_set_flee_state(self_obj, 1);
end

procedure Daren01
begin
	gsay_reply(SCRIPT_HIGHTOWR, 101);
	giq_option(4, SCRIPT_HIGHTOWR, 102, Daren02, NEUTRAL_REACTION);
	if (global_var(GVAR_KILL_MERCHANT) == 1) then begin
		giq_option(4, SCRIPT_HIGHTOWR, 103, Daren03, NEUTRAL_REACTION);
	end
	giq_option(4, SCRIPT_HIGHTOWR, message_str(SCRIPT_HIGHTOWR, 104) + proto_data(obj_pid(dude_obj), 1) + message_str(SCRIPT_HIGHTOWR, 105), Daren04, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_HIGHTOWR, 106, Daren07, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_HIGHTOWR, 107, Daren06, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_HIGHTOWR, 108, Daren06, NEUTRAL_REACTION);
end

procedure Daren02
begin
	gsay_reply(SCRIPT_HIGHTOWR, 109);
	if (global_var(GVAR_KILL_MERCHANT) == 1) then begin
		giq_option(4, SCRIPT_HIGHTOWR, 110, DarenCombat, BAD_REACTION);
	end
	giq_option(4, SCRIPT_HIGHTOWR, 111, Daren05, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_HIGHTOWR, 112, Daren06, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_HIGHTOWR, 113, Daren06, NEUTRAL_REACTION);
end

procedure Daren03
begin
	gsay_reply(SCRIPT_HIGHTOWR, 114);
	giq_option(4, SCRIPT_HIGHTOWR, 115, Daren06, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_HIGHTOWR, 116, Daren07, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_HIGHTOWR, 117, DarenCombat, BAD_REACTION);
	giq_option(4, SCRIPT_HIGHTOWR, 118, Daren06, NEUTRAL_REACTION);
end

procedure Daren04
begin
	gsay_message(SCRIPT_HIGHTOWR, message_str(SCRIPT_HIGHTOWR, 119) + proto_data(obj_pid(dude_obj), 1) + message_str(SCRIPT_HIGHTOWR, 120), BAD_REACTION);
	call DarenEndLeon;
end

procedure Daren05
begin
	gsay_reply(SCRIPT_HIGHTOWR, 121);
	giq_option(4, SCRIPT_HIGHTOWR, 122, Daren07, NEUTRAL_REACTION);
	if (item_caps_total(dude_obj) >= 100) then begin
		giq_option(4, SCRIPT_HIGHTOWR, 123, Daren05a, NEUTRAL_REACTION);
	end
	giq_option(4, SCRIPT_HIGHTOWR, 124, Daren06, NEUTRAL_REACTION);
end

procedure Daren05a
begin
	variable LVar0 := 0;
	LVar0 := item_caps_adjust(dude_obj, -100);
	gsay_message(SCRIPT_HIGHTOWR, 125, BAD_REACTION);
	call DarenEndLeon;
end

procedure Daren06
begin
	gsay_message(SCRIPT_HIGHTOWR, 126, BAD_REACTION);
	call DarenEndLeon;
end

procedure Daren07
begin
	gsay_message(SCRIPT_HIGHTOWR, 127, BAD_REACTION);
	call DarenCombat;
end

procedure DarenCombat
begin
	call combat;
end

procedure DarenEndLeon
begin
	set_map_var(1, 1);
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end