#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure use_p_proc;
procedure chairend;
procedure look_at_p_proc;
procedure description_p_proc;


procedure start
begin
	variable LVar0 := 0;
	if (script_action == use_proc) then begin
		call use_p_proc;
	end
	else begin
		if (script_action == description_proc) then begin
			call description_p_proc;
		end
		else begin
			if (script_action == look_at_proc) then begin
				call look_at_p_proc;
			end
		end
	end
end

procedure use_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_HOUSCHAR, 102));
end

procedure chairend
begin
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_HOUSCHAR, 101));
end

procedure description_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_HOUSCHAR, 100));
end