#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure damage_p_proc;
procedure George01;
procedure George01a;
procedure George01b;
procedure George02;
procedure George02a;
procedure George03;
procedure George04;
procedure George05;
procedure George06;
procedure George07;
procedure George08;
procedure GeorgeEnd;

variable hostile1;
variable Only_Once := 1;
variable lastTraverse;
variable currentLocation;
variable hereBefore;
variable visible := 1;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure start
begin
	if (Only_Once) then begin
		Only_Once := 0;
		set_map_var(3, 0);
		if (global_var(GVAR_KILL_MERCHANT) == 5) then begin
			set_obj_visibility(self_obj, 1);
			visible := 0;
			set_map_var(3, 1);
		end
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 42);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_GUARD_SADISTIC);
	end
	if (script_action == look_at_proc) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == pickup_proc) then begin
			call pickup_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
			else begin
				if (script_action == critter_proc) then begin
					call critter_p_proc;
				end
				else begin
					if (script_action == destroy_proc) then begin
						call destroy_p_proc;
					end
					else begin
						if (script_action == damage_proc) then begin
							call damage_p_proc;
						end
					end
				end
			end
		end
	end
end

procedure combat
begin
	hostile1 := 1;
end

procedure critter_p_proc
begin
	if (visible == 0) then begin
		script_overrides;
	end
	else begin
		if (hostile1) then begin
			hostile1 := 0;
			attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
		end
		if (map_var(5) == 1) then begin
			if ((obj_can_hear_obj(self_obj, dude_obj) == 1) or (obj_can_see_obj(self_obj, dude_obj) == 1)) then begin
				call combat;
			end
		end
		else begin
			if ((game_time_hour >= 1900) or (game_time_hour < 600)) then begin
				if ((obj_can_hear_obj(self_obj, dude_obj) == 1) or (obj_can_see_obj(self_obj, dude_obj) == 1)) then begin
					dialogue_system_enter;
				end
				else begin
					if ((global_var(GVAR_KILL_MERCHANT) == 1) or (global_var(GVAR_STEAL_NECKLACE) == 1)) then begin
						set_map_var(3, 1);
						if (((game_time / 10) - lastTraverse) >= 20) then begin
							lastTraverse := game_time / 10;
							if (currentLocation == 0) then begin
								currentLocation := 1;
								animate_move_obj_to_tile(self_obj, 19516, ANIMATE_WALK);
							end
							else begin
								currentLocation := 0;
								animate_move_obj_to_tile(self_obj, 22529, ANIMATE_WALK);
							end
						end
					end
					else begin
						if (tile_num(self_obj) != 22529) then begin
							animate_move_obj_to_tile(self_obj, 22529, ANIMATE_WALK);
						end
					end
				end
			end
			else begin
				if (tile_num(self_obj) != 22529) then begin
					animate_move_obj_to_tile(self_obj, 22529, ANIMATE_WALK);
				end
				if (map_var(2) == 1) then begin
					dialogue_system_enter;
				end
			end
		end
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		hostile1 := 1;
	end
end

procedure talk_p_proc
begin
	call Get_Reaction;
	if ((game_time_hour >= 1900) or (game_time_hour < 600)) then begin
		float_msg(self_obj, message_str(SCRIPT_HTWRGRGE, 118), FLOAT_MSG_RED);
		call combat;
	end
	else begin
		if (global_var(GVAR_ENEMY_HUB) == 1) then begin
			float_msg(self_obj, message_str(SCRIPT_HTWRGRGE, 120), FLOAT_MSG_RED);
			call combat;
		end
		else begin
			if (map_var(2) == 1) then begin
				set_map_var(2, 0);
				call George08;
			end
			else begin
				if (hereBefore == 0) then begin
					hereBefore := 1;
					start_gdialog(SCRIPT_HTWRGRGE, self_obj, 4, -1, -1);
					gsay_start;
					call George01;
					gsay_end;
					end_dialogue;
				end
				else begin
					call George07;
				end
			end
		end
	end
end

procedure destroy_p_proc
begin
	set_map_var(4, 1);
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_HTWRGRGE, 100));
end

procedure damage_p_proc
begin
	set_map_var(5, 1);
end

procedure George01
begin
	gsay_reply(SCRIPT_HTWRGRGE, 101);
	giq_option(4, SCRIPT_HTWRGRGE, 103, George01a, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_HTWRGRGE, 104, George01b, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_HTWRGRGE, 105, George06, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_HTWRGRGE, 102, George06, NEUTRAL_REACTION);
end

procedure George01a
begin
	if (is_success(roll_vs_skill(dude_obj, 14, -10))) then begin
		call George03;
	end
	else begin
		call George02;
	end
end

procedure George01b
begin
	if (is_success(roll_vs_skill(dude_obj, 14, 10))) then begin
		call George05;
	end
	else begin
		call George02;
	end
end

procedure George02
begin
	gsay_reply(SCRIPT_HTWRGRGE, 106);
	giq_option(4, SCRIPT_HTWRGRGE, 107, George02a, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_HTWRGRGE, 108, George06, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_HTWRGRGE, 109, George03, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_HTWRGRGE, 110, GeorgeEnd, NEUTRAL_REACTION);
end

procedure George02a
begin
	if (is_success(roll_vs_skill(dude_obj, 14, 0))) then begin
		call George03;
	end
	else begin
		call George06;
	end
end

procedure George03
begin
	set_map_var(3, 1);
	gsay_message(SCRIPT_HTWRGRGE, 111, NEUTRAL_REACTION);
end

procedure George04
begin
	gsay_message(SCRIPT_HTWRGRGE, 112, BAD_REACTION);
end

procedure George05
begin
	set_map_var(3, 1);
	gsay_message(SCRIPT_HTWRGRGE, 113, NEUTRAL_REACTION);
end

procedure George06
begin
	gsay_message(SCRIPT_HTWRGRGE, 114, BAD_REACTION);
end

procedure George07
begin
	float_msg(self_obj, message_str(SCRIPT_HTWRGRGE, random(114, 117)), FLOAT_MSG_RED);
end

procedure George08
begin
	float_msg(self_obj, message_str(SCRIPT_HTWRGRGE, 119), FLOAT_MSG_RED);
end

procedure GeorgeEnd
begin
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end