#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure damage_p_proc;
procedure IrwinTalks;
procedure IrwinAccept;
procedure IrwinEnd;
procedure Irwin00;
procedure Irwin01;
procedure Irwin02;
procedure Irwin03;
procedure Irwin04;
procedure Irwin05;
procedure Irwin06;
procedure Irwin07;

variable hostile1;
variable Only_Once := 1;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure start
begin
	if (Only_Once) then begin
		Only_Once := 0;
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 41);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_HUB_PEASANTS);
	end
	if (script_action == look_at_proc) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == pickup_proc) then begin
			call pickup_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
			else begin
				if (script_action == critter_proc) then begin
					call critter_p_proc;
				end
				else begin
					if (script_action == destroy_proc) then begin
						call destroy_p_proc;
					end
				end
			end
		end
	end
end

procedure combat
begin
	hostile1 := 1;
end

procedure critter_p_proc
begin
	if (hostile1) then begin
		hostile1 := 0;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
	if (global_var(GVAR_DESTROY_MASTER_3) == 501) then begin
		if (tile_num(self_obj) != 27969) then begin
			animate_move_obj_to_tile(self_obj, 27969, ANIMATE_WALK);
		end
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		hostile1 := 1;
	end
end

procedure talk_p_proc
begin
	variable LVar0 := 0;
	call Get_Reaction;
	call IrwinTalks;
end

procedure destroy_p_proc
begin
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_IRWIN, 100));
end

procedure damage_p_proc
begin
	variable LVar0 := 0;
	LVar0 := obj_pid(source_obj);
	if (party_member_obj(LVar0) != 0) then begin
		set_global_var(GVAR_ENEMY_HUB, 1);
	end
end

procedure IrwinTalks
begin
	if (global_var(GVAR_DESTROY_MASTER_3) == 0) then begin
		start_gdialog(SCRIPT_IRWIN, self_obj, 4, -1, -1);
		gsay_start;
		call Irwin00;
		gsay_end;
		end_dialogue;
	end
	else begin
		if ((global_var(GVAR_DESTROY_MASTER_3) == 1) or (global_var(GVAR_DESTROY_MASTER_3) == 2)) then begin
			start_gdialog(SCRIPT_IRWIN, self_obj, 4, -1, -1);
			gsay_start;
			call Irwin05;
			gsay_end;
			end_dialogue;
		end
		else begin
			float_msg(self_obj, message_str(SCRIPT_IRWIN, 117), FLOAT_MSG_YELLOW);
		end
	end
end

procedure IrwinAccept
begin
	gsay_message(SCRIPT_IRWIN, 109, NEUTRAL_REACTION);
	set_global_var(GVAR_DESTROY_MASTER_3, 1);
	game_time_advance(10 * 60 * 60 * 1);
	load_map("hubmis1.map", 1);
end

procedure IrwinEnd
begin
end

procedure Irwin00
begin
	gsay_reply(SCRIPT_IRWIN, 101);
	giq_option(4, SCRIPT_IRWIN, 102, Irwin01, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_IRWIN, 103, Irwin03, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_IRWIN, 104, IrwinEnd, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_IRWIN, 118, Irwin07, NEUTRAL_REACTION);
end

procedure Irwin01
begin
	if (get_pc_stat(1) < 5) then begin
		gsay_message(SCRIPT_IRWIN, 105, NEUTRAL_REACTION);
	end
	else begin
		call Irwin02;
	end
end

procedure Irwin02
begin
	gsay_reply(SCRIPT_IRWIN, 106);
	giq_option(4, SCRIPT_IRWIN, 107, IrwinAccept, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_IRWIN, 108, Irwin04, NEUTRAL_REACTION);
end

procedure Irwin03
begin
	gsay_message(SCRIPT_IRWIN, 110, NEUTRAL_REACTION);
end

procedure Irwin04
begin
	gsay_message(SCRIPT_IRWIN, 111, NEUTRAL_REACTION);
end

procedure Irwin05
begin
	gsay_reply(SCRIPT_IRWIN, 112);
	giq_option(4, SCRIPT_IRWIN, 113, Irwin06, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_IRWIN, 114, IrwinEnd, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_IRWIN, 120, Irwin06, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_IRWIN, 121, IrwinEnd, NEUTRAL_REACTION);
end

procedure Irwin06
begin
	variable LVar0 := 0;
	if (global_var(GVAR_DESTROY_MASTER_3) == 2) then begin
		gsay_message(SCRIPT_IRWIN, 115, NEUTRAL_REACTION);
		LVar0 := create_object_sid(241, 0, 0, -1);
		add_obj_to_inven(dude_obj, LVar0);
		give_exp_points(500);
		set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 2);
		set_global_var(GVAR_DESTROY_MASTER_3, 501);
	end
	else begin
		gsay_message(SCRIPT_IRWIN, 116, NEUTRAL_REACTION);
	end
end

procedure Irwin07
begin
	gsay_message(SCRIPT_IRWIN, 119, NEUTRAL_REACTION);
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end