#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure use_p_proc;

variable initialized1;

import variable ladder_down;


procedure start
begin
	if (not(initialized1)) then begin
		ladder_down := self_obj;
		initialized1 := 1;
	end
	else begin
		if (script_action == use_proc) then begin
			call use_p_proc;
		end
	end
end

procedure use_p_proc
begin
	move_to(source_obj, 12498, 1);
	if (combat_is_initialized and (source_obj != dude_obj)) then begin
		critter_stop_attacking(source_obj);
	end
end