#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure map_update_p_proc;


procedure start
begin
	if (script_action == map_update_proc) then begin
		call map_update_p_proc;
	end
end

procedure map_update_p_proc
begin
	variable LVar0 := 0;
	if (global_var(GVAR_VATS_ALERT) and (local_var(0) == 0)) then begin
		set_local_var(0, 1);
		if (obj_pid(self_obj) == 33555260) then begin
			LVar0 := create_object_sid(33555340, tile_num(self_obj), elevation(self_obj), -1);
		end
		else begin
			LVar0 := create_object_sid(33555339, tile_num(self_obj), elevation(self_obj), -1);
		end
	end
end