#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure description_p_proc;
procedure use_p_proc;
procedure use_skill_on_p_proc;


procedure start
begin
	if (script_action == description_proc) then begin
		call description_p_proc;
	end
	else begin
		if (script_action == use_proc) then begin
			call use_p_proc;
		end
		else begin
			if (script_action == use_skill_on_proc) then begin
				call use_skill_on_p_proc;
			end
		end
	end
end

procedure description_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_LIBCOMP, 100));
end

procedure use_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_LIBCOMP, 105));
end

procedure use_skill_on_p_proc
begin
	if (action_being_used == 12) then begin
		script_overrides;
		display_msg(message_str(SCRIPT_LIBCOMP, 101));
		if (local_var(0)) then begin
			display_msg(message_str(SCRIPT_LIBCOMP, 102));
			game_time_advance(game_ticks(3600));
		end
		else begin
			if (is_success(do_check(dude_obj, 4, 0))) then begin
				gfade_out(600);
				display_msg(message_str(SCRIPT_LIBCOMP, 103));
				game_time_advance(game_ticks(21600));
				give_exp_points(350);
				set_local_var(0, 1);
				gfade_in(600);
			end
			else begin
				gfade_out(600);
				display_msg(message_str(SCRIPT_LIBCOMP, 104));
				game_time_advance(game_ticks(21600));
				set_local_var(0, 1);
				gfade_in(600);
			end
		end
	end
end