#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure do_stuff;


procedure start
begin
	if (script_action == look_at_proc) then begin
		script_overrides;
		display_msg(message_str(SCRIPT_MACHIV, 100));
	end
	else begin
		if (script_action == use_proc) then begin
			script_overrides;
			call do_stuff;
		end
		else begin
			if (script_action == use_skill_on_proc) then begin
				if (action_being_used == 12) then begin
					script_overrides;
					call do_stuff;
				end
			end
		end
	end
end

procedure do_stuff
begin
	variable LVar0 := 0;
	LVar0 := random(1, 4);
	if (LVar0 == 1) then begin
		display_msg(message_str(SCRIPT_MACHIV, 101));
	end
	else begin
		if (LVar0 == 2) then begin
			display_msg(message_str(SCRIPT_MACHIV, 102));
		end
		else begin
			if (LVar0 == 3) then begin
				display_msg(message_str(SCRIPT_MACHIV, 103));
			end
			else begin
				if (LVar0 == 4) then begin
					display_msg(message_str(SCRIPT_MACHIV, 104));
				end
			end
		end
	end
end