#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure dead00;


procedure start
begin
	variable LVar0 := 0;
	if (script_action == description_proc) then begin
		script_overrides;
		call dead00;
	end
	else begin
		if (script_action == look_at_proc) then begin
			script_overrides;
			display_msg(message_str(SCRIPT_MANGLED, 100));
		end
	end
end

procedure dead00
begin
	if (is_success(do_check(dude_obj, 4, 0))) then begin
		display_msg(message_str(SCRIPT_MANGLED, 101));
	end
end