#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure Lighting;
procedure Darkness;
procedure add_party;
procedure update_party;
procedure remove_party;

variable party_elevation;
variable dude_start_hex;

export variable Ian_ptr;
export variable Dog_ptr;
export variable Tycho_ptr;
export variable Katja_ptr;
export variable Tandi_ptr;
export variable Skill_Used;
export variable Key_Used;
export variable Master_Has_Armed;
export variable Bomb_Armed;
export variable Master_ptr;
export variable signal_mutants;
export variable Master_Has_Activated;

variable Player_Elevation;
variable mutan1_ptr;
variable mutan2_ptr;
variable mutan_ptr;
variable stuff;
variable cur_count;
variable prev_count;

procedure Invasion;


procedure start
begin
if (script_action == map_enter_proc) then begin
    Player_Elevation := elevation(dude_obj);
    if (Player_Elevation == 0) then begin
      if ((game_time_hour >= 700) and (game_time_hour < 1800) and (metarule(22, 0) == 0)) then begin
        if (map_var(10) == 0) then begin
          set_map_var(10, 1);
          mutan_ptr := create_object_sid(16777408, 0, 0, 524);
          critter_attempt_placement(mutan_ptr, 20532, 0);
          critter_add_trait(mutan_ptr, 1, 6, 34);
          stuff := create_object_sid(15, 0, 0, -1);
          add_obj_to_inven(mutan_ptr, stuff);
          stuff := create_object_sid(39, 0, 0, -1);
          add_obj_to_inven(mutan_ptr, stuff);
          stuff := create_object_sid(40, 0, 0, -1);
          add_obj_to_inven(mutan_ptr, stuff);
          mutan_ptr := create_object_sid(16777408, 0, 0, 524);
          critter_attempt_placement(mutan_ptr, 19337, 0);
          critter_add_trait(mutan_ptr, 1, 6, 34);
          stuff := create_object_sid(28, 0, 0, -1);
          add_obj_to_inven(mutan_ptr, stuff);
          stuff := create_object_sid(39, 0, 0, -1);
          add_obj_to_inven(mutan_ptr, stuff);
          stuff := create_object_sid(40, 0, 0, -1);
          add_obj_to_inven(mutan_ptr, stuff);
          mutan_ptr := create_object_sid(16777408, 0, 0, 524);
          critter_attempt_placement(mutan_ptr, 18740, 0);
          critter_add_trait(mutan_ptr, 1, 6, 34);
          stuff := create_object_sid(28, 0, 0, -1);
          add_obj_to_inven(mutan_ptr, stuff);
          stuff := create_object_sid(39, 0, 0, -1);
          add_obj_to_inven(mutan_ptr, stuff);
          stuff := create_object_sid(40, 0, 0, -1);
          add_obj_to_inven(mutan_ptr, stuff);
          mutan_ptr := create_object_sid(16777408, 0, 0, 524);
          critter_attempt_placement(mutan_ptr, 21339, 0);
          critter_add_trait(mutan_ptr, 1, 6, 34);
          stuff := create_object_sid(28, 0, 0, -1);
          add_obj_to_inven(mutan_ptr, stuff);
          stuff := create_object_sid(39, 0, 0, -1);
          add_obj_to_inven(mutan_ptr, stuff);
          stuff := create_object_sid(40, 0, 0, -1);
          add_obj_to_inven(mutan_ptr, stuff);
        end
      end
    end
    if (global_var(GVAR_LOAD_MAP_INDEX) == 2) then begin
      override_map_start(112, 84, 0, 3);
    end
    else begin
      if (global_var(GVAR_LOAD_MAP_INDEX) == 3) then begin
        override_map_start(140, 78, 1, 4);
      end
      else begin
        if (global_var(GVAR_LOAD_MAP_INDEX) == 5) then begin
          override_map_start(140, 78, 0, 4);
        end
        else begin
          if (global_var(GVAR_LOAD_MAP_INDEX) == 12) then begin
            override_map_start(55, 68, 0, 5);
            if (metarule(22, 0) == 0) then begin
              create_object_sid(16777363, 13854, 0, 53);
              mutan_ptr := create_object_sid(16777409, 0, 0, 524);
              critter_attempt_placement(mutan_ptr, 15468, 0);
              critter_add_trait(mutan_ptr, 1, 6, 55);
              stuff := create_object_sid(15, 0, 0, -1);
              add_obj_to_inven(mutan_ptr, stuff);
              stuff := create_object_sid(39, 0, 0, -1);
              add_obj_to_inven(mutan_ptr, stuff);
              stuff := create_object_sid(40, 0, 0, -1);
              add_obj_to_inven(mutan_ptr, stuff);
              mutan_ptr := create_object_sid(16777409, 0, 0, 524);
              critter_attempt_placement(mutan_ptr, 15450, 0);
              critter_add_trait(mutan_ptr, 1, 6, 55);
              stuff := create_object_sid(15, 0, 0, -1);
              add_obj_to_inven(mutan_ptr, stuff);
              stuff := create_object_sid(39, 0, 0, -1);
              add_obj_to_inven(mutan_ptr, stuff);
              stuff := create_object_sid(40, 0, 0, -1);
              add_obj_to_inven(mutan_ptr, stuff);
            end
          end
          else begin
            override_map_start(112, 84, 0, 3);
          end
        end
      end
    end
    call Darkness;
    call add_party;
  end
  if (script_action == map_update_proc) then begin
    call Darkness;
    if (global_var(GVAR_COUNTDOWN_TO_DESTRUCTION) != 0) then begin
      cur_count := 240 - ((game_time / 10) - global_var(GVAR_COUNTDOWN_TO_DESTRUCTION));
      if (cur_count != prev_count) then begin
        display_msg(message_str(SCRIPT_MASTER2, 100) + cur_count + message_str(SCRIPT_MASTER2, 101));
        prev_count := cur_count;
      end
      if (((game_time / 10) - global_var(GVAR_COUNTDOWN_TO_DESTRUCTION)) > 240) then begin
        display_msg(message_str(SCRIPT_MASTER2, 106));
        play_gmovie(MOVIE_CATHEXP);
        metarule(13, 0);
      end
    end
    call update_party;
  end
  if (script_action == map_exit_proc) then begin
    kill_critter_type(16777408, 0);
    call remove_party;
  end
end

procedure Lighting
begin
  variable LVar0 := 0;
  LVar0 := game_time_hour;
  if ((LVar0 >= 600) and (LVar0 < 700)) then begin
    set_light_level(LVar0 - 600 + 40);
  end
  else begin
    if ((LVar0 >= 700) and (LVar0 < 1800)) then begin
      set_light_level(100);
    end
    else begin
      if ((LVar0 >= 1800) and (LVar0 < 1900)) then begin
        set_light_level(100 - (LVar0 - 1800));
      end
      else begin
        set_light_level(40);
      end
    end
  end
end

procedure Darkness
begin
  set_light_level(40);
end

procedure add_party
begin
  variable LVar0 := 0;
  variable LVar1 := 0;
  party_elevation := elevation(dude_obj);
  if (global_var(GVAR_TANDI_STATUS) == 5) then begin
    if (Tandi_ptr == 0) then begin
    end
    critter_add_trait(Tandi_ptr, 1, 6, 0);
  end
end

procedure update_party
begin
  variable LVar0 := 0;
  variable LVar1 := 0;
  if (elevation(dude_obj) != party_elevation) then begin
    party_elevation := elevation(dude_obj);
    if (global_var(GVAR_IAN_STATUS) == 2) then begin
      if (Ian_ptr == 0) then begin
      end
      else begin
        move_to(Ian_ptr, tile_num_in_direction(tile_num(dude_obj), 1, 2), elevation(dude_obj));
      end
    end
    if (global_var(GVAR_DOG_EMPATHY)) then begin
      if (Dog_ptr == 0) then begin
      end
      else begin
        move_to(Dog_ptr, tile_num_in_direction(tile_num(dude_obj), 2, 1), elevation(dude_obj));
      end
    end
    if (global_var(GVAR_HERNANDEZ_STATUS) == 2) then begin
      if (Tycho_ptr == 0) then begin
      end
      else begin
        move_to(Tycho_ptr, tile_num_in_direction(tile_num(dude_obj), 3, 2), elevation(dude_obj));
      end
    end
    if (global_var(GVAR_KATJA_STATUS) == 2) then begin
      if (Katja_ptr == 0) then begin
      end
      else begin
        move_to(Katja_ptr, tile_num_in_direction(tile_num(dude_obj), 4, 2), elevation(dude_obj));
      end
    end
    if (global_var(GVAR_TANDI_STATUS) == 5) then begin
      if (Tandi_ptr == 0) then begin
      end
      else begin
        move_to(Tandi_ptr, tile_num_in_direction(tile_num(dude_obj), 4, 4), elevation(dude_obj));
      end
    end
  end
end

procedure remove_party
begin
  if (global_var(GVAR_IAN_STATUS) == 2) then begin
    set_global_var(GVAR_IAN_STATUS, 2);
  end
  if (global_var(GVAR_DOG_EMPATHY)) then begin
    set_global_var(GVAR_DOG_EMPATHY, 1);
  end
  if (global_var(GVAR_HERNANDEZ_STATUS) == 2) then begin
    set_global_var(GVAR_HERNANDEZ_STATUS, 2);
  end
  if (global_var(GVAR_KATJA_STATUS) == 2) then begin
    set_global_var(GVAR_KATJA_STATUS, 2);
  end
  if (global_var(GVAR_TANDI_STATUS) == 5) then begin
  end
end

procedure Invasion
begin
  if (not(global_var(GVAR_MASTER_BLOWN) == 2)) then begin
    if (global_var(GVAR_NECROPOLIS_INVADED_DATE) > (game_time / (10 * 60 * 60 * 24))) then begin
      set_global_var(GVAR_NECROPOLIS_INVADED, 1);
    end
    if (global_var(GVAR_THE_HUB_INVADED_DATE) > (game_time / (10 * 60 * 60 * 24))) then begin
      set_global_var(GVAR_HUB_INVADED, 1);
    end
    if (global_var(GVAR_BROTHERHOOD_INVADED_DATE) > (game_time / (10 * 60 * 60 * 24))) then begin
      set_global_var(GVAR_BROTHERHOOD_INVADED, 1);
    end
    if (global_var(GVAR_JUNKTOWN_INVADED_DATE) > (game_time / (10 * 60 * 60 * 24))) then begin
      set_global_var(GVAR_JUNKTOWN_INVADED, 1);
    end
    if (global_var(GVAR_SHADY_SANDS_INVADED_DATE) > (game_time / (10 * 60 * 60 * 24))) then begin
      set_global_var(GVAR_SHADY_SANDS_INVADED, 1);
    end
    if (global_var(GVAR_VAULT_13_INVADED_DATE) <= 0) then begin
      set_global_var(GVAR_VAULT_INVADED, 1);
    end
    if (global_var(GVAR_FOLLOWERS_INVADED_DATE) > (game_time / (10 * 60 * 60 * 24))) then begin
      set_global_var(GVAR_FOLLOWERS_INVADED, 1);
    end
  end
end