#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure Mathia01;
procedure Mathia02;
procedure Mathia03;
procedure Mathia04;
procedure Mathia05;
procedure Mathia06;
procedure Mathia07;
procedure Mathia08;
procedure Mathia08a;
procedure Mathia08b;
procedure Mathia08c;
procedure Mathia08d;
procedure Mathia08e;
procedure Mathia09;
procedure Mathia10;
procedure Mathia11;
procedure MathiaEnd;

variable hostile1;
variable Only_Once := 1;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure start
begin
	if (Only_Once) then begin
		Only_Once := 0;
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 44);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_BROTHERHOOD_PALADIN);
	end
	if (script_action == look_at_proc) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == pickup_proc) then begin
			call pickup_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
			else begin
				if (script_action == critter_proc) then begin
					call critter_p_proc;
				end
				else begin
					if (script_action == destroy_proc) then begin
						call destroy_p_proc;
					end
				end
			end
		end
	end
end

procedure combat
begin
	hostile1 := 1;
end

procedure critter_p_proc
begin
	if (obj_can_see_obj(self_obj, dude_obj)) then begin
		if ((map_var(20) == 1) and (local_var(5) == 0)) then begin
			dialogue_system_enter;
		end
		if ((map_var(19) == 1) and (local_var(6) == 0)) then begin
			dialogue_system_enter;
		end
	end
	if (global_var(GVAR_ENEMY_BROTHERHOOD)) then begin
		hostile1 := 1;
	end
	if (tile_distance_objs(self_obj, dude_obj) > 12) then begin
		hostile1 := 0;
	end
	if (hostile1) then begin
		set_global_var(GVAR_ENEMY_BROTHERHOOD, 1);
		hostile1 := 0;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		hostile1 := 1;
	end
end

procedure talk_p_proc
begin
	call Get_Reaction;
	start_gdialog(SCRIPT_MATHIA, self_obj, 4, -1, -1);
	gsay_start;
	if ((map_var(19) == 1) and (local_var(6) == 0)) then begin
		set_local_var(6, 1);
		call Mathia09;
	end
	else begin
		if ((map_var(20) == 1) and (local_var(5) == 0)) then begin
			call Mathia08;
		end
		else begin
			if (local_var(4) == 0) then begin
				set_local_var(4, 1);
				call Mathia01;
			end
			else begin
				call Mathia06;
			end
		end
	end
	gsay_end;
	end_dialogue;
end

procedure destroy_p_proc
begin
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_MATHIA, 100));
end

procedure Mathia01
begin
	gsay_reply(SCRIPT_MATHIA, 101);
	giq_option(-3, SCRIPT_MATHIA, 102, Mathia05, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 103, Mathia02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 104, MathiaEnd, NEUTRAL_REACTION);
end

procedure Mathia02
begin
	gsay_reply(SCRIPT_MATHIA, 105);
	giq_option(4, SCRIPT_MATHIA, 106, Mathia03, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 107, Mathia04, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 108, MathiaEnd, NEUTRAL_REACTION);
end

procedure Mathia03
begin
	gsay_reply(SCRIPT_MATHIA, 109);
	giq_option(4, SCRIPT_MATHIA, 110, Mathia04, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 111, MathiaEnd, NEUTRAL_REACTION);
end

procedure Mathia04
begin
	gsay_reply(SCRIPT_MATHIA, 112);
	giq_option(4, SCRIPT_MATHIA, 113, MathiaEnd, NEUTRAL_REACTION);
end

procedure Mathia05
begin
	gsay_message(SCRIPT_MATHIA, 114, BAD_REACTION);
end

procedure Mathia06
begin
	gsay_reply(SCRIPT_MATHIA, 115);
	giq_option(-3, SCRIPT_MATHIA, 116, Mathia05, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 117, Mathia02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 118, MathiaEnd, NEUTRAL_REACTION);
end

procedure Mathia07
begin
	gsay_reply(SCRIPT_MATHIA, 119);
	giq_option(-3, SCRIPT_MATHIA, 120, Mathia11, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_MATHIA, 121, combat, BAD_REACTION);
	giq_option(4, SCRIPT_MATHIA, 122, Mathia11, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 123, combat, BAD_REACTION);
end

procedure Mathia08
begin
	gsay_reply(SCRIPT_MATHIA, 124);
	giq_option(-3, SCRIPT_MATHIA, 125, Mathia05, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 126, Mathia08a, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 127, Mathia08b, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 128, Mathia08c, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 129, Mathia08d, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 130, Mathia08e, NEUTRAL_REACTION);
end

procedure Mathia08a
begin
	variable LVar0 := 0;
	set_local_var(5, 1);
	LVar0 := create_object_sid(143, 0, 0, -1);
	add_obj_to_inven(dude_obj, LVar0);
	gsay_message(SCRIPT_MATHIA, 131, NEUTRAL_REACTION);
end

procedure Mathia08b
begin
	variable LVar0 := 0;
	set_local_var(5, 1);
	LVar0 := create_object_sid(13, 0, 0, -1);
	add_obj_to_inven(dude_obj, LVar0);
	gsay_message(SCRIPT_MATHIA, 131, NEUTRAL_REACTION);
end

procedure Mathia08c
begin
	variable LVar0 := 0;
	set_local_var(5, 1);
	LVar0 := create_object_sid(16, 0, 0, -1);
	add_obj_to_inven(dude_obj, LVar0);
	gsay_message(SCRIPT_MATHIA, 131, NEUTRAL_REACTION);
end

procedure Mathia08d
begin
	variable LVar0 := 0;
	set_local_var(5, 1);
	LVar0 := create_object_sid(235, 0, 0, -1);
	add_obj_to_inven(dude_obj, LVar0);
	gsay_message(SCRIPT_MATHIA, 131, NEUTRAL_REACTION);
end

procedure Mathia08e
begin
	variable LVar0 := 0;
	set_local_var(5, 1);
	LVar0 := create_object_sid(116, 0, 0, -1);
	add_obj_to_inven(dude_obj, LVar0);
	gsay_message(SCRIPT_MATHIA, 131, NEUTRAL_REACTION);
end

procedure Mathia09
begin
	gsay_reply(SCRIPT_MATHIA, 132);
	giq_option(4, SCRIPT_MATHIA, 133, Mathia10, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_MATHIA, 134, MathiaEnd, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_MATHIA, 116, Mathia05, NEUTRAL_REACTION);
end

procedure Mathia10
begin
	gsay_reply(SCRIPT_MATHIA, 135);
	giq_option(4, SCRIPT_MATHIA, 134, MathiaEnd, NEUTRAL_REACTION);
end

procedure Mathia11
begin
	set_global_var(GVAR_BECOME_AN_INITIATE, 5);
	world_map;
end

procedure MathiaEnd
begin
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end