#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure goto01;
procedure goto02;
procedure goto03;
procedure goto04;
procedure goto05;
procedure goto06;
procedure goto07;
procedure goto08;
procedure goto09;
procedure goto10;
procedure goto11;
procedure explode;
procedure escape;
procedure dialog_end;

variable hostile1;
variable Only_Once := 1;
variable target_hex;
variable said;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure start
begin
	if (Only_Once) then begin
		Only_Once := 0;
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 2);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_PEASANT);
	end
	if (script_action == look_at_proc) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == pickup_proc) then begin
			call pickup_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
			else begin
				if (script_action == critter_proc) then begin
					call critter_p_proc;
				end
				else begin
					if (script_action == destroy_proc) then begin
						call destroy_p_proc;
					end
				end
			end
		end
	end
end

procedure combat
begin
	hostile1 := 1;
end

procedure critter_p_proc
begin
	if (tile_num(self_obj) < 25000) then begin
		call explode;
	end
	else begin
		if ((map_var(2) == 1) or (map_var(7) == 1)) then begin
			call escape;
		end
		else begin
			if (hostile1 == 1) then begin
				attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
			end
		end
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		hostile1 := 1;
	end
end

procedure talk_p_proc
begin
	call Get_Reaction;
	start_gdialog(SCRIPT_MLPRISON, self_obj, 4, -1, -1);
	gsay_start;
	if (obj_pid(critter_inven_obj(dude_obj, 0)) == 113) then begin
		if (local_var(5) == 1) then begin
			call goto05;
		end
		else begin
			call goto01;
		end
		set_local_var(5, 1);
	end
	else begin
		if (local_var(4) == 1) then begin
			call goto09;
		end
		else begin
			call goto07;
		end
		set_local_var(4, 1);
	end
	gsay_end;
	end_dialogue;
end

procedure destroy_p_proc
begin
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
end

procedure look_at_p_proc
begin
	script_overrides;
end

procedure goto01
begin
	gsay_reply(SCRIPT_MLPRISON, 108);
	giq_option(-3, SCRIPT_MLPRISON, 109, goto02, BAD_REACTION);
	giq_option(4, SCRIPT_MLPRISON, 110, goto03, BAD_REACTION);
	giq_option(4, SCRIPT_MLPRISON, 111, goto04, BAD_REACTION);
end

procedure goto02
begin
	gsay_message(SCRIPT_MLPRISON, 112, BAD_REACTION);
	call dialog_end;
end

procedure goto03
begin
	gsay_message(SCRIPT_MLPRISON, 113, BAD_REACTION);
	call dialog_end;
end

procedure goto04
begin
	gsay_message(SCRIPT_MLPRISON, 128, BAD_REACTION);
	call dialog_end;
end

procedure goto05
begin
	gsay_reply(SCRIPT_MLPRISON, 114);
	giq_option(-3, SCRIPT_MLPRISON, 115, goto02, BAD_REACTION);
	giq_option(4, SCRIPT_MLPRISON, 116, goto06, BAD_REACTION);
	giq_option(4, SCRIPT_MLPRISON, 117, dialog_end, BAD_REACTION);
end

procedure goto06
begin
	gsay_message(SCRIPT_MLPRISON, 118, BAD_REACTION);
	call dialog_end;
end

procedure goto07
begin
	gsay_reply(SCRIPT_MLPRISON, 119);
	giq_option(-3, SCRIPT_MLPRISON, 115, goto02, BAD_REACTION);
	giq_option(4, SCRIPT_MLPRISON, 120, goto08, BAD_REACTION);
end

procedure goto08
begin
	gsay_message(SCRIPT_MLPRISON, 122, BAD_REACTION);
	call dialog_end;
end

procedure goto09
begin
	gsay_reply(SCRIPT_MLPRISON, 123);
	giq_option(-3, SCRIPT_MLPRISON, 115, goto02, BAD_REACTION);
	giq_option(4, SCRIPT_MLPRISON, 124, goto11, BAD_REACTION);
	giq_option(4, SCRIPT_MLPRISON, 125, dialog_end, BAD_REACTION);
end

procedure goto10
begin
	gsay_message(SCRIPT_MLPRISON, 126, BAD_REACTION);
	call dialog_end;
end

procedure goto11
begin
	gsay_message(SCRIPT_MLPRISON, 127, BAD_REACTION);
	call dialog_end;
end

procedure explode
begin
	critter_dmg(self_obj, 128, 6);
end

procedure escape
begin
	if (said == 0) then begin
		said := 1;
		float_msg(self_obj, message_str(SCRIPT_MLPRISON, 107), FLOAT_MSG_RED);
	end
	target_hex := 22912;
	animate_move_obj_to_tile(self_obj, target_hex, ANIMATE_RUN);
end

procedure dialog_end
begin
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end