#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure spatial_p_proc;


procedure start
begin
	if (script_action == spatial_proc) then begin
		call spatial_p_proc;
	end
end

procedure spatial_p_proc
begin
	if (not(is_success(do_check(source_obj, 5, 0)))) then begin
		critter_dmg(source_obj, random(15, 40), 3);
	end
end