#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure use_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;


procedure start
begin
	if (script_action == use_proc) then begin
		call use_p_proc;
	end
	else begin
		if ((script_action == description_proc) or (script_action == look_at_proc)) then begin
		end
	end
end

procedure use_p_proc
begin
	add_obj_to_inven(dude_obj, create_object_sid(21, 0, 0, -1));
	display_msg(message_str(SCRIPT_MUTEJAR, 101));
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_MUTEJAR, 100));
end

procedure description_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_MUTEJAR, 100));
end