#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>


procedure start
begin
	if (script_action == use_obj_on_proc) then begin
		script_overrides;
		display_msg(message_str(SCRIPT_MUTFRUIT, 100));
		critter_heal(dude_obj, random(1, 6));
		radiation_inc(dude_obj, 10);
		rm_obj_from_inven(dude_obj, self_obj);
	end
end