#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure critter_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure Orfeo0;
procedure Orfeo1;
procedure Orfeo2;
procedure Orfeo3;
procedure Orfeoend;
procedure combat;

variable initialized1;
variable hostile1;


procedure start
begin
	if (not(initialized1)) then begin
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 20);
		initialized1 := 1;
	end
	else begin
		if (script_action == critter_proc) then begin
			call critter_p_proc;
		end
		else begin
			if (script_action == destroy_proc) then begin
				call destroy_p_proc;
			end
			else begin
				if (script_action == look_at_proc) then begin
					call look_at_p_proc;
				end
				else begin
					if (script_action == pickup_proc) then begin
						call pickup_p_proc;
					end
					else begin
						if (script_action == talk_proc) then begin
							call talk_p_proc;
						end
					end
				end
			end
		end
	end
end

procedure critter_p_proc
begin
	if (hostile1) then begin
		hostile1 := 0;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
end

procedure destroy_p_proc
begin
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_BAD_MONSTER, global_var(GVAR_BAD_MONSTER) + 1);
		if ((global_var(GVAR_BAD_MONSTER) % 6) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 1);
		end
	end
end

procedure look_at_p_proc
begin
	if (local_var(0)) then begin
		script_overrides;
		display_msg(message_str(SCRIPT_ORFEO, 100));
	end
end

procedure pickup_p_proc
begin
	hostile1 := 1;
end

procedure talk_p_proc
begin
	script_overrides;
	if (local_var(0)) then begin
		call Orfeo3;
	end
	else begin
		set_local_var(0, 1);
		start_gdialog(SCRIPT_ORFEO, self_obj, 4, -1, -1);
		gsay_start;
		call Orfeo0;
		gsay_end;
		end_dialogue;
	end
end

procedure Orfeo0
begin
	gsay_reply(SCRIPT_ORFEO, 101);
	giq_option(-3, SCRIPT_ORFEO, 102, combat, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_ORFEO, 103, Orfeo1, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_ORFEO, 104, Orfeo2, NEUTRAL_REACTION);
end

procedure Orfeo1
begin
	gsay_message(SCRIPT_ORFEO, 105, NEUTRAL_REACTION);
	call combat;
end

procedure Orfeo2
begin
	gsay_message(SCRIPT_ORFEO, 106, NEUTRAL_REACTION);
	call combat;
end

procedure Orfeo3
begin
	float_msg(self_obj, message_str(SCRIPT_ORFEO, 107), FLOAT_MSG_NORMAL);
	call combat;
end

procedure Orfeoend
begin
end

procedure combat
begin
	hostile1 := hostile1 + 1;
end