#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure PaladinARandom;
procedure PaladinABackground;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure time_p_proc;

variable only_once := 1;
variable hostile1;


procedure start
begin
	if (only_once) then begin
		only_once := 0;
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 44);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_BROTHERHOOD_PALADIN);
		add_timer_event(self_obj, game_ticks(300), 1);
	end
	if (script_action == look_at_proc) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == pickup_proc) then begin
			call pickup_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
		end
	end
	if (script_action == timed_event_proc) then begin
		call time_p_proc;
	end
	else begin
		if (script_action == critter_proc) then begin
			call critter_p_proc;
		end
		else begin
			if (script_action == destroy_proc) then begin
				call destroy_p_proc;
			end
		end
	end
end

procedure PaladinARandom
begin
	variable LVar0 := 0;
	variable LVar1 := 0;
	if (not(LVar0)) then begin
		LVar0 := random(1, 9);
	end
	if (LVar0 > 10) then begin
		LVar0 := 1;
	end
	LVar1 := message_str(SCRIPT_PALADINA, 101);
	if (LVar0 == 2) then begin
		LVar1 := message_str(SCRIPT_PALADINA, 102);
	end
	else begin
		if (LVar0 == 3) then begin
			LVar1 := message_str(SCRIPT_PALADINA, 103);
		end
		else begin
			if (LVar0 == 4) then begin
				LVar1 := message_str(SCRIPT_PALADINA, 104) + proto_data(obj_pid(dude_obj), 1) + message_str(SCRIPT_PALADINA, 105);
			end
			else begin
				if (LVar0 == 5) then begin
					LVar1 := message_str(SCRIPT_PALADINA, 106);
				end
				else begin
					if (LVar0 == 6) then begin
						LVar1 := message_str(SCRIPT_PALADINA, 107);
					end
					else begin
						if (LVar0 == 7) then begin
							LVar1 := message_str(SCRIPT_PALADINA, 108);
						end
						else begin
							if (LVar0 == 8) then begin
								LVar1 := message_str(SCRIPT_PALADINA, 109);
							end
							else begin
								if (LVar0 == 9) then begin
									LVar1 := message_str(SCRIPT_PALADINA, 110);
								end
								else begin
									LVar0 := 1;
								end
							end
						end
					end
				end
			end
		end
	end
	LVar0 := LVar0 + 1;
	float_msg(self_obj, LVar1, FLOAT_MSG_NORMAL);
end

procedure PaladinABackground
begin
	variable LVar0 := 0;
	add_timer_event(self_obj, game_ticks(300), 1);
	if (random(0, 1)) then begin
		LVar0 := message_str(SCRIPT_PALADINA, 112);
	end
	else begin
		LVar0 := message_str(SCRIPT_PALADINA, 113);
	end
	float_msg(self_obj, LVar0, FLOAT_MSG_NORMAL);
end

procedure critter_p_proc
begin
	if (global_var(GVAR_ENEMY_BROTHERHOOD)) then begin
		hostile1 := 1;
	end
	if (tile_distance_objs(self_obj, dude_obj) > 12) then begin
		hostile1 := 0;
	end
	if (hostile1) then begin
		set_global_var(GVAR_ENEMY_BROTHERHOOD, 1);
		hostile1 := 0;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		hostile1 := 1;
	end
end

procedure talk_p_proc
begin
	call PaladinARandom;
end

procedure destroy_p_proc
begin
	set_global_var(GVAR_ENEMY_BROTHERHOOD, 1);
	rm_timer_event(self_obj);
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_PALADINA, 100));
end

procedure time_p_proc
begin
	call PaladinABackground;
end