#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>


procedure start
begin
	if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
		script_overrides;
		if ((global_var(GVAR_BROTHERHOOD_OF_STEEL) == 2) and is_success(do_check(dude_obj, 1, 0))) then begin
			display_msg(message_str(SCRIPT_PERNPWR, 100));
		end
		else begin
			display_msg(message_str(SCRIPT_PERNPWR, 101));
		end
	end
	else begin
		if (script_action == use_skill_on_proc) then begin
			script_overrides;
			if (action_being_used == 7) then begin
				if (is_success(roll_vs_skill(dude_obj, 7, 0))) then begin
					display_msg(message_str(SCRIPT_PERNPWR, 102));
				end
				else begin
					display_msg(message_str(SCRIPT_PERNPWR, 103));
				end
			end
			else begin
				display_msg(message_str(SCRIPT_PERNPWR, 104));
			end
		end
	end
end