#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>

variable temp;


procedure start
begin
	if (script_action == spatial_proc) then begin
		if (source_obj == dude_obj) then begin
			if (local_var(0) < 1) then begin
				set_local_var(0, 1);
				display_msg(message_str(SCRIPT_RUBCHIP, 101));
				display_msg(message_str(SCRIPT_RUBCHIP, 100));
				give_exp_points(500);
				display_msg(message_str(SCRIPT_RUBCHIP, 102) + 500 + message_str(SCRIPT_RUBCHIP, 103));
			end
		end
	end
end