#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure do_dialogue;


procedure start
begin
	if (script_action == talk_proc) then begin
		call do_dialogue;
	end
	else begin
		if (script_action == description_proc) then begin
			script_overrides;
			display_msg(message_str(SCRIPT_SSWELL, 100));
		end
		else begin
			if (script_action == destroy_proc) then begin
				set_global_var(GVAR_QUEST_PEOPLE, 1);
			end
		end
	end
end

procedure do_dialogue
begin
	start_gdialog(-1, 14, 4, -1, -1);
	sayMessage(0, message_str(SCRIPT_SSWELL, 101));
	end_dialogue;
end