#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure pickup_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure chairend;


procedure start
begin
	variable LVar0 := 0;
	if (script_action == pickup_proc) then begin
		call pickup_p_proc;
	end
	else begin
		if (script_action == description_proc) then begin
			call description_p_proc;
		end
		else begin
			if (script_action == look_at_proc) then begin
				call look_at_p_proc;
			end
		end
	end
end

procedure pickup_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_SDRESSER, 102));
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_SDRESSER, 101));
end

procedure description_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_SDRESSER, 100));
end

procedure chairend
begin
end