#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>

variable Only_once := 1;
variable hostile1;


procedure start
begin
	if (Only_once) then begin
		Only_once := 0;
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 0);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_GUARD);
		if (global_var(GVAR_SETH_STATUS) == 3) then begin
			set_obj_visibility(self_obj, 1);
		end
	end
	if (script_action == talk_proc) then begin
		if (global_var(GVAR_RADSCORPION_SEED) == 2) then begin
			float_msg(self_obj, message_str(SCRIPT_SETH2, 102), FLOAT_MSG_YELLOW);
		end
		else begin
			float_msg(self_obj, message_str(SCRIPT_SETH2, 101), FLOAT_MSG_YELLOW);
		end
	end
	else begin
		if (script_action == critter_proc) then begin
			if (hostile1) then begin
				hostile1 := 0;
				attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
			end
			if (tile_distance_objs(self_obj, dude_obj) > 3) then begin
				animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(dude_obj), random(0, 5), 1), ANIMATE_WALK);
			end
		end
		else begin
			if (script_action == pickup_proc) then begin
				hostile1 := 1;
			end
			else begin
				if (script_action == look_at_proc) then begin
					script_overrides;
					display_msg(message_str(SCRIPT_SETH2, 100));
				end
				else begin
					if (script_action == destroy_proc) then begin
						set_global_var(GVAR_SETH_STATUS, 3);
						if (source_obj == dude_obj) then begin
							if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
								set_global_var(GVAR_BERSERKER_REPUTATION, 1);
								set_global_var(GVAR_CHAMPION_REPUTATION, 0);
							end
							if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
								set_global_var(GVAR_CHAMPION_REPUTATION, 1);
								set_global_var(GVAR_BERSERKER_REPUTATION, 0);
							end
							set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
							if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
								set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
							end
						end
					end
				end
			end
		end
	end
end