#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure goto00;
procedure goto01;
procedure goto02;
procedure goto03;
procedure goto04;
procedure goto05;
procedure goto06;
procedure goto07;
procedure goto08;
procedure goto09;
procedure goto10;
procedure goto11;
procedure goto12;
procedure goto13;
procedure goto14;
procedure goto15;
procedure goto16;
procedure goto16b;
procedure goto17;
procedure goto18;
procedure goto19;
procedure goto20;
procedure goto20b;
procedure goto21;
procedure anger;
procedure gotoend;
procedure gotostory;

variable hostile1;
variable item;
variable Pick;
variable only_once := 1;
variable message;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure start
begin
	if (only_once) then begin
		only_once := 0;
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 44);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_BROTHERHOOD_SCRIBE);
	end
	if (script_action == look_at_proc) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == pickup_proc) then begin
			call pickup_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
			else begin
				if (script_action == critter_proc) then begin
					call critter_p_proc;
				end
				else begin
					if (script_action == destroy_proc) then begin
						call destroy_p_proc;
					end
				end
			end
		end
	end
end

procedure combat
begin
	hostile1 := 1;
end

procedure critter_p_proc
begin
	if (global_var(GVAR_ENEMY_BROTHERHOOD)) then begin
		hostile1 := 1;
	end
	if (tile_distance_objs(self_obj, dude_obj) > 12) then begin
		hostile1 := 0;
	end
	if (hostile1) then begin
		set_global_var(GVAR_ENEMY_BROTHERHOOD, 1);
		hostile1 := 0;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		hostile1 := 1;
	end
end

procedure talk_p_proc
begin
	call Get_Reaction;
	start_gdialog(SCRIPT_SOPHIA, self_obj, 4, -1, -1);
	gsay_start;
	if (local_var(4)) then begin
		if (local_var(1) < 2) then begin
			call goto20;
		end
		else begin
			call goto16;
		end
	end
	else begin
		set_local_var(4, 1);
		if (map_var(0) == 1) then begin
			call goto14;
		end
		else begin
			call goto00;
		end
	end
	gsay_end;
	end_dialogue;
end

procedure destroy_p_proc
begin
	set_global_var(GVAR_ENEMY_BROTHERHOOD, 1);
	rm_timer_event(self_obj);
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_SOPHIA, 100));
end

procedure goto00
begin
	gsay_reply(SCRIPT_SOPHIA, 301);
	giq_option(-3, SCRIPT_SOPHIA, 302, goto01, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 303, goto02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 304, goto03, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 305, goto02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 306, anger, BAD_REACTION);
end

procedure goto01
begin
	gsay_message(SCRIPT_SOPHIA, 307, BAD_REACTION);
end

procedure goto02
begin
	gsay_reply(SCRIPT_SOPHIA, 308);
	if (global_var(GVAR_NECROP_WATER_CHIP_TAKEN) != 1) then begin
		giq_option(4, SCRIPT_SOPHIA, 309, goto04, NEUTRAL_REACTION);
	end
	giq_option(4, SCRIPT_SOPHIA, 310, goto05, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 311, goto06, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 312, gotoend, NEUTRAL_REACTION);
	if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
		giq_option(4, SCRIPT_SOPHIA, 313, anger, BAD_REACTION);
	end
end

procedure goto03
begin
	gsay_reply(SCRIPT_SOPHIA, 314);
	giq_option(4, SCRIPT_SOPHIA, 315, gotoend, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 316, goto07, NEUTRAL_REACTION);
end

procedure goto04
begin
	gsay_reply(SCRIPT_SOPHIA, 317);
	giq_option(4, SCRIPT_SOPHIA, 318, goto07, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 319, goto06, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 320, anger, BAD_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 321, gotoend, NEUTRAL_REACTION);
end

procedure goto05
begin
	gsay_reply(SCRIPT_SOPHIA, 322);
	giq_option(4, SCRIPT_SOPHIA, 323, gotoend, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 324, goto08, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 325, goto09, NEUTRAL_REACTION);
end

procedure goto06
begin
	gsay_reply(SCRIPT_SOPHIA, 326);
	giq_option(4, SCRIPT_SOPHIA, 327, goto11, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 328, goto11, NEUTRAL_REACTION);
	if (local_var(6) != 1) then begin
		giq_option(4, SCRIPT_SOPHIA, 329, goto12, NEUTRAL_REACTION);
	end
	giq_option(4, SCRIPT_SOPHIA, 330, goto07, NEUTRAL_REACTION);
end

procedure goto07
begin
	gsay_reply(SCRIPT_SOPHIA, 331);
	if (local_var(6) != 1) then begin
		giq_option(4, SCRIPT_SOPHIA, 332, goto12, NEUTRAL_REACTION);
	end
	giq_option(4, SCRIPT_SOPHIA, 333, goto09, NEUTRAL_REACTION);
	if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
		giq_option(4, SCRIPT_SOPHIA, 334, goto01, BAD_REACTION);
	end
	giq_option(4, SCRIPT_SOPHIA, 335, goto05, NEUTRAL_REACTION);
end

procedure goto08
begin
	gsay_message(SCRIPT_SOPHIA, 336, NEUTRAL_REACTION);
end

procedure goto09
begin
	gsay_reply(SCRIPT_SOPHIA, 337);
	if (local_var(6) != 1) then begin
		giq_option(4, SCRIPT_SOPHIA, 338, goto12, GOOD_REACTION);
	end
	giq_option(4, SCRIPT_SOPHIA, 339, Down_React, BAD_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 341, goto01, BAD_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 342, goto10, NEUTRAL_REACTION);
end

procedure goto10
begin
	gsay_message(SCRIPT_SOPHIA, 343, NEUTRAL_REACTION);
end

procedure goto11
begin
	gsay_reply(SCRIPT_SOPHIA, 344);
	giq_option(4, SCRIPT_SOPHIA, 345, gotoend, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 346, goto13, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 347, Down_React, BAD_REACTION);
end

procedure goto12
begin
	set_local_var(6, 1);
	item := create_object_sid(215, 0, 0, -1);
	add_obj_to_inven(dude_obj, item);
	gsay_reply(SCRIPT_SOPHIA, 348);
	giq_option(4, SCRIPT_SOPHIA, 349, gotoend, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 350, Down_React, BAD_REACTION);
end

procedure goto13
begin
	gsay_reply(SCRIPT_SOPHIA, 351);
	if (local_var(6) != 1) then begin
		giq_option(4, SCRIPT_SOPHIA, 352, goto12, GOOD_REACTION);
	end
	giq_option(4, SCRIPT_SOPHIA, 349, gotoend, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 353, anger, BAD_REACTION);
end

procedure goto14
begin
	gsay_reply(SCRIPT_SOPHIA, 301);
	giq_option(-3, SCRIPT_SOPHIA, 302, goto01, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 303, goto02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 330, goto15, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 306, anger, BAD_REACTION);
end

procedure goto15
begin
	gsay_reply(SCRIPT_SOPHIA, 359);
	giq_option(4, SCRIPT_SOPHIA, 360, goto07, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 361, anger, BAD_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 362, Down_React, BAD_REACTION);
end

procedure goto16
begin
	gsay_reply(SCRIPT_SOPHIA, 364);
	giq_option(4, SCRIPT_SOPHIA, 365, goto17, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 366, goto16b, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 367, gotoend, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_SOPHIA, 302, goto01, NEUTRAL_REACTION);
end

procedure goto16b
begin
	if (local_var(6) != 1) then begin
		call goto12;
	end
	else begin
		call goto18;
	end
end

procedure goto17
begin
	gsay_reply(SCRIPT_SOPHIA, 368);
	giq_option(4, SCRIPT_SOPHIA, 369, gotoend, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 316, goto07, NEUTRAL_REACTION);
end

procedure goto18
begin
	gsay_reply(SCRIPT_SOPHIA, 374);
	giq_option(4, SCRIPT_SOPHIA, 369, gotoend, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 350, Down_React, BAD_REACTION);
end

procedure goto19
begin
	gsay_reply(SCRIPT_SOPHIA, 374);
	giq_option(4, SCRIPT_SOPHIA, 369, gotoend, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 350, Down_React, BAD_REACTION);
end

procedure goto20
begin
	gsay_reply(SCRIPT_SOPHIA, 377);
	giq_option(4, SCRIPT_SOPHIA, 378, gotoend, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 379, goto20b, GOOD_REACTION);
	giq_option(-3, SCRIPT_SOPHIA, 302, goto01, NEUTRAL_REACTION);
end

procedure goto20b
begin
	if (is_success(roll_vs_skill(dude_obj, 14, -10))) then begin
		call goto21;
	end
	else begin
		call goto01;
	end
end

procedure goto21
begin
	call Up_React;
	gsay_reply(SCRIPT_SOPHIA, 380);
	giq_option(4, SCRIPT_SOPHIA, 381, goto17, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 382, goto16b, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_SOPHIA, 383, gotoend, NEUTRAL_REACTION);
end

procedure anger
begin
	call Down_React;
	call goto01;
end

procedure gotoend
begin
end

procedure gotostory
begin
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end