#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure do_dialogue;
procedure supercbt;
procedure superx;
procedure super00;

variable Hostile;
variable init_teams;


procedure start
begin
	if (not(init_teams)) then begin
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 34);
		init_teams := 1;
	end
	if (script_action == talk_proc) then begin
		call do_dialogue;
	end
	else begin
		if (script_action == pickup_proc) then begin
			Hostile := 1;
		end
		else begin
			if (script_action == critter_proc) then begin
				if (Hostile) then begin
					Hostile := 0;
					attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
				end
				else begin
					if (global_var(GVAR_NECROPOLIS_INVADED) == 0) then begin
						set_obj_visibility(self_obj, 1);
					end
					else begin
						if ((game_time_hour >= 1900) or (game_time_hour < 600) and (tile_num(self_obj) != 24929)) then begin
							animate_move_obj_to_tile(self_obj, 24929, ANIMATE_WALK);
						end
						if ((game_time_hour >= 700) and (game_time_hour < 1800) and (tile_num(self_obj) != 25915)) then begin
							animate_move_obj_to_tile(self_obj, 25915, ANIMATE_WALK);
						end
					end
				end
			end
			else begin
				if (script_action == destroy_proc) then begin
					set_global_var(GVAR_SUPER_MUTANTS_KILLED, global_var(GVAR_SUPER_MUTANTS_KILLED) + 1);
					if (source_obj == dude_obj) then begin
						if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
							set_global_var(GVAR_BERSERKER_REPUTATION, 1);
							set_global_var(GVAR_CHAMPION_REPUTATION, 0);
						end
						if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
							set_global_var(GVAR_CHAMPION_REPUTATION, 1);
							set_global_var(GVAR_BERSERKER_REPUTATION, 0);
						end
						set_global_var(GVAR_BAD_MONSTER, global_var(GVAR_BAD_MONSTER) + 1);
						if ((global_var(GVAR_BAD_MONSTER) % 6) == 0) then begin
							set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 1);
						end
					end
				end
				else begin
					if (script_action == look_at_proc) then begin
						display_msg(message_str(SCRIPT_SUPER, 100));
					end
				end
			end
		end
	end
end

procedure do_dialogue
begin
	start_gdialog(SCRIPT_SUPER, self_obj, 4, -1, -1);
	gsay_start;
	if (local_var(0)) then begin
		call super00;
	end
	else begin
		set_local_var(0, 1);
		call super00;
	end
	gsay_end;
	end_dialogue;
end

procedure supercbt
begin
	Hostile := 1;
end

procedure superx
begin
	call supercbt;
end

procedure super00
begin
	gsay_reply(SCRIPT_SUPER, 101);
	giq_option(3, SCRIPT_SUPER, 102, superx, NEUTRAL_REACTION);
	giq_option(3, SCRIPT_SUPER, 103, supercbt, NEUTRAL_REACTION);
	giq_option(-3, SCRIPT_SUPER, 104, supercbt, NEUTRAL_REACTION);
end