#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure Troy00;
procedure Troy01;
procedure Troy02;
procedure Troy03;
procedure Troy04;
procedure Troy05;
procedure Troy06;
procedure Troy07;
procedure Troy08;

variable hostile1;
variable Only_Once := 1;
variable TalkToPlayer;

procedure Get_Reaction;
procedure React_To_Level;
procedure Level_To_React;
procedure Up_React;
procedure Down_React;
procedure Bottom_React;
procedure Top_React;
procedure Big_Up_React;
procedure Big_Down_React;
procedure Up_React_Level;
procedure Down_React_Level;
procedure Goodbyes;

variable exit_line;


procedure start
begin
	if (Only_Once) then begin
		Only_Once := 0;
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 34);
		critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_SUPER_MUTANT_AGGRESSIVE);
	end
	if (script_action == look_at_proc) then begin
		call look_at_p_proc;
	end
	else begin
		if (script_action == pickup_proc) then begin
			call pickup_p_proc;
		end
		else begin
			if (script_action == talk_proc) then begin
				call talk_p_proc;
			end
			else begin
				if (script_action == critter_proc) then begin
					call critter_p_proc;
				end
				else begin
					if (script_action == destroy_proc) then begin
						call destroy_p_proc;
					end
				end
			end
		end
	end
end

procedure combat
begin
	hostile1 := 1;
end

procedure critter_p_proc
begin
	if (hostile1) then begin
		hostile1 := 0;
		attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
	end
	if ((TalkToPlayer == 1) and (tile_distance_objs(self_obj, dude_obj) <= 3)) then begin
		dialogue_system_enter;
	end
	if (map_var(3) == 1) then begin
		set_map_var(3, 0);
		TalkToPlayer := 1;
		reg_anim_func(1, 1);
		reg_anim_obj_move_to_obj(self_obj, dude_obj, -1);
		reg_anim_func(3, 0);
	end
end

procedure pickup_p_proc
begin
	if (source_obj == dude_obj) then begin
		hostile1 := 1;
	end
end

procedure talk_p_proc
begin
	call Get_Reaction;
	if (TalkToPlayer == 1) then begin
		start_gdialog(SCRIPT_TROY, self_obj, 4, -1, -1);
		gsay_start;
		call Troy00;
		gsay_end;
		end_dialogue;
	end
	else begin
		display_msg(message_str(SCRIPT_TROY, 132));
	end
end

procedure destroy_p_proc
begin
	if (source_obj == dude_obj) then begin
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_global_var(GVAR_BERSERKER_REPUTATION, 1);
			set_global_var(GVAR_CHAMPION_REPUTATION, 0);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_global_var(GVAR_CHAMPION_REPUTATION, 1);
			set_global_var(GVAR_BERSERKER_REPUTATION, 0);
		end
		set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
		if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
			set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
		end
	end
end

procedure look_at_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_TROY, 100));
end

procedure Troy00
begin
	gsay_reply(SCRIPT_TROY, 101);
	giq_option(7, SCRIPT_TROY, 102, Troy01, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_TROY, 103, Troy01, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_TROY, 104, Troy02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_TROY, 105, Troy03, BAD_REACTION);
	giq_option(4, SCRIPT_TROY, 106, Troy04, BAD_REACTION);
	giq_option(-3, SCRIPT_TROY, 107, Troy05, NEUTRAL_REACTION);
end

procedure Troy01
begin
	gsay_reply(SCRIPT_TROY, 108);
	giq_option(4, SCRIPT_TROY, 109, Troy06, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_TROY, 110, Troy02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_TROY, 111, Troy03, BAD_REACTION);
	giq_option(4, SCRIPT_TROY, 112, Troy07, BAD_REACTION);
end

procedure Troy02
begin
	gsay_message(SCRIPT_TROY, 113, NEUTRAL_REACTION);
	game_time_advance(game_ticks(60 * 60 * 24 * 14));
	set_global_var(GVAR_ENTERING_VATS_HOW, 1);
	load_map(32, 5);
end

procedure Troy03
begin
	set_global_var(GVAR_ENEMY_CATHEDRAL, 1);
	gsay_message(SCRIPT_TROY, 114, NEUTRAL_REACTION);
	call combat;
end

procedure Troy04
begin
	gsay_reply(SCRIPT_TROY, 115);
	giq_option(4, SCRIPT_TROY, 116, Troy02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_TROY, 117, Troy03, BAD_REACTION);
	giq_option(4, SCRIPT_TROY, 118, Troy08, BAD_REACTION);
	giq_option(4, SCRIPT_TROY, 119, Troy07, BAD_REACTION);
end

procedure Troy05
begin
	gsay_reply(SCRIPT_TROY, 120);
	giq_option(4, SCRIPT_TROY, 121, Troy02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_TROY, 122, Troy03, NEUTRAL_REACTION);
end

procedure Troy06
begin
	gsay_reply(SCRIPT_TROY, 123);
	giq_option(4, SCRIPT_TROY, 124, Troy02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_TROY, 125, Troy03, BAD_REACTION);
	giq_option(4, SCRIPT_TROY, 126, Troy07, BAD_REACTION);
end

procedure Troy07
begin
	set_global_var(GVAR_ENEMY_CATHEDRAL, 1);
	gsay_message(SCRIPT_TROY, 127, BAD_REACTION);
	call combat;
end

procedure Troy08
begin
	gsay_reply(SCRIPT_TROY, 128);
	giq_option(4, SCRIPT_TROY, 129, Troy02, NEUTRAL_REACTION);
	giq_option(4, SCRIPT_TROY, 120, Troy03, BAD_REACTION);
	giq_option(4, SCRIPT_TROY, 121, Troy07, BAD_REACTION);
end

procedure Get_Reaction
begin
	if (local_var(2) == 0) then begin
		set_local_var(0, 50);
		set_local_var(1, 2);
		set_local_var(2, 1);
		set_local_var(0, local_var(0) + (5 * get_critter_stat(dude_obj, 3)) - 25);
		set_local_var(0, local_var(0) + (10 * has_trait(0, dude_obj, 10)));
		if (has_trait(0, dude_obj, 39)) then begin
			if (global_var(GVAR_PLAYER_REPUTATION) > 0) then begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		else begin
			if (local_var(3) == 1) then begin
				set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUTATION));
			end
			else begin
				set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUTATION));
			end
		end
		if (global_var(GVAR_CHILDKILLER_REPUTATION) > 2) then begin
			set_local_var(0, local_var(0) - 30);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_BAD_MONSTER) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) + 20);
		end
		if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
			set_local_var(0, local_var(0) - 20);
		end
		call React_To_Level;
	end
end

procedure React_To_Level
begin
	if (local_var(0) <= 25) then begin
		set_local_var(1, 1);
	end
	else begin
		if (local_var(0) <= 75) then begin
			set_local_var(1, 2);
		end
		else begin
			set_local_var(1, 3);
		end
	end
end

procedure Level_To_React
begin
	if (local_var(1) == 1) then begin
		set_local_var(0, random(1, 25));
	end
	else begin
		if (local_var(1) == 2) then begin
			set_local_var(0, random(26, 75));
		end
		else begin
			set_local_var(0, random(76, 100));
		end
	end
end

procedure Up_React
begin
	set_local_var(0, local_var(0) + 10);
	call React_To_Level;
end

procedure Down_React
begin
	set_local_var(0, local_var(0) - 10);
	call React_To_Level;
end

procedure Bottom_React
begin
	set_local_var(1, 1);
	set_local_var(0, 1);
end

procedure Top_React
begin
	set_local_var(0, 100);
	set_local_var(1, 3);
end

procedure Big_Up_React
begin
	set_local_var(0, local_var(0) + 25);
	call React_To_Level;
end

procedure Big_Down_React
begin
	set_local_var(0, local_var(0) - 25);
	call React_To_Level;
end

procedure Up_React_Level
begin
	set_local_var(1, local_var(1) + 1);
	if (local_var(1) > 3) then begin
		set_local_var(1, 3);
	end
	call Level_To_React;
end

procedure Down_React_Level
begin
	set_local_var(1, local_var(1) - 1);
	if (local_var(1) < 1) then begin
		set_local_var(1, 1);
	end
	call Level_To_React;
end

procedure Goodbyes
begin
	exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end