#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure spatial_p_proc;


procedure start
begin
	if (script_action == spatial_proc) then begin
		call spatial_p_proc;
	end
end

procedure spatial_p_proc
begin
	if (source_obj == dude_obj) then begin
		if (not(local_var(0))) then begin
			display_msg(message_str(SCRIPT_VALTOP, 100));
			set_local_var(0, 1);
		end
	end
end