#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure use_p_proc;
procedure use_skill_on_p_proc;


procedure start
begin
	if (script_action == use_proc) then begin
		call use_p_proc;
	end
	else begin
		if (script_action == use_skill_on_proc) then begin
			call use_skill_on_p_proc;
		end
	end
end

procedure use_p_proc
begin
	script_overrides;
	display_msg(message_str(SCRIPT_VALTCOMP, 100));
end

procedure use_skill_on_p_proc
begin
	if (action_being_used == 12) then begin
		script_overrides;
		if (elevation(self_obj) == 0) then begin
			display_msg(message_str(SCRIPT_VALTCOMP, 102));
		end
		else begin
			display_msg(message_str(SCRIPT_VALTCOMP, 101));
		end
	end
end