#include <define.h>

//#define NAME                    SCRIPT_

#include <command.h>
//#include <ModReact.h>



procedure start;
#include <push.h>
procedure spatial_p_proc;


procedure start
begin
	if (script_action == spatial_proc) then begin
		call spatial_p_proc;
	end
end

procedure spatial_p_proc
begin
	if (map_var(7) == 1) then begin
		display_msg(message_str(SCRIPT_VATWARN, 100));
		float_msg(dude_obj, message_str(SCRIPT_VATWARN, 101), FLOAT_MSG_LIGHT_RED);
	end
end