# Alchemist: long phrases should be split and require some smooyhing.

{100}{}{Tu vois Lex, Chef du clan de pillards Vipères.}
{101}{}{Un type énorme avec un comportement antipathique. Il te lance un regard furieux.}
{102}{}{[...Tu te réveilles progressivement et regardes autour. Tu vois un endroit inconnu, trois tentes et plusieurs personnes à proximité. Il semblerait que tu aies réussi à te réveiller avant qu'ils ne te vident les poches. Tes yeux s'arrêtent sur l'homme posté à coté de toi] Oh, notre acheteur malchanceux se réveille !}
{103}{}{[Plus]}
{104}{}{Qu'est-ce que ca sera ? Tu nous donnes tous tes caps et on te laisse partir. Ou on joue aux cowboys.}
{105}{}{Et quelles garanties j'ai de quitter cet endroit vivant après vous avoir donner l'argent ?}
{106}{}{J'ai toujours adoré les westerns.}
{107}{}{Cowboys.}
{108}{}{Parole de Pillard !}
{109}{}{Je pense que je peux te faire confiance. Tiens, prends ça. [Tu lui donnes tes économies]}
{110}{}{Ces mots ne veulent rien dire pour moi.}
{111}{}{Tiens donc, un têtu ? J'aime plutôt ça. Je pense que les gars vont s'amuser un peu avec toi alors.}
{112}{}{Si tu ne crois pas ces mots, tu devrais croire nos flingues ! Une mauviette comme toi n'est pas un gros challenge pour le gang tout entier !}
{113}{}{Alors, je vais devoir te tuer. Pour être sur que personne ne jase. Adieu.}
{114}{}{Bon gars. C'est une sage décision. T'es libre de partir.}

