{100}{}{Voici Kyle.}
{101}{}{Hey mec, comment ça va ? Toujours en train de crapaüter... T'es pas fatigué ? Il serait p'tet temps de penser à t'offrir une caisse ! Prêt à lacher de la monnaie ?}
{102}{}{Comment je vais ? J'me suis jamais mieux senti ! Mais est-ce que t'as vraiment des véhicules en état de marche ? La monnaie c'est pas un problème.}
{103}{}{Et si je te découpais un peu, je pourrais avoir une voiture gratuitement?}
{104}{}{C'est une bonne question. On s'voit plus tard.}
{105}{}{Hmmm.... Je suis pas sûr. Un acheteur un peu plus riche ne serait pas de refus. Ecoute, pourquoi tu ne reviens pas plus tard, quand t'auras plus de caps ?}
{106}{}{Crois moi, un ami a un VRAI business. C'est le seul mec dans les wastelands qui peut te vendre une caisse. C'est pas très loin d'ici. Ca devrait prendre une journée pour y aller. Il se sert de sa propre maison comme garage... Pour 400 caps je pourrais te montrer le chemin.}
{107}{}{Marché conclu. Montre moi le chemin et je m'occupe du reste.}
{108}{}{Désolé, Kyle. J'ai des choses plus importantes à faire.}
{109}{}{OK, je vais t'y emmener. Le client est roi! Suis moi. [Il empoche les 400 caps]}
{110}{}{Je savais que t'allais te débiner. Tout le monde est effrayé de voyager avec tant d'argent. Mais mes amis peuvent t'aider! [Tu viens de comprendre que quelquechose ne tourne pas rond, quand soudainement un violent coup sur la tête te fait perdre connaissance. La dernière chose que tu as ressenti c'est d'avoir été trainé quelquepart...]}
{111}{}{Ecoute, tu ne m'impressionnes vraiment pas.}
{112}{}{Je devrais chercher un client plus convenable...}
