uses
  Windows;
  
const
Lift_Number_0_Button1_Map = $2EE7C + $000;
Lift_Number_0_Button1_Elevation = $2EE7C + $004;
Lift_Number_0_Button1_Tile = $2EE7C + $008;
Lift_Number_0_Button2_Map = $2EE7C + $00C;
Lift_Number_0_Button2_Elevation = $2EE7C + $010;
Lift_Number_0_Button2_Tile = $2EE7C + $014;
Lift_Number_0_Button3_Map = $2EE7C + $018;
Lift_Number_0_Button3_Elevation = $2EE7C + $01C;
Lift_Number_0_Button3_Tile = $2EE7C + $020;
Lift_Number_0_Button4_Map = $2EE7C + $024;
Lift_Number_0_Button4_Elevation = $2EE7C + $028;
Lift_Number_0_Button4_Tile = $2EE7C + $02C;
Lift_Number_1_Button1_Map = $2EE7C + $030;
Lift_Number_1_Button1_Elevation = $2EE7C + $034;
Lift_Number_1_Button1_Tile = $2EE7C + $038;
Lift_Number_1_Button2_Map = $2EE7C + $03C;
Lift_Number_1_Button2_Elevation = $2EE7C + $040;
Lift_Number_1_Button2_Tile = $2EE7C + $044;
Lift_Number_1_Button3_Map = $2EE7C + $048;
Lift_Number_1_Button3_Elevation = $2EE7C + $04C;
Lift_Number_1_Button3_Tile = $2EE7C + $050;
Lift_Number_1_Button4_Map = $2EE7C + $054;
Lift_Number_1_Button4_Elevation = $2EE7C + $058;
Lift_Number_1_Button4_Tile = $2EE7C + $05C;
Lift_Number_2_Button1_Map = $2EE7C + $060;
Lift_Number_2_Button1_Elevation = $2EE7C + $064;
Lift_Number_2_Button1_Tile = $2EE7C + $068;
Lift_Number_2_Button2_Map = $2EE7C + $06C;
Lift_Number_2_Button2_Elevation = $2EE7C + $070;
Lift_Number_2_Button2_Tile = $2EE7C + $074;
Lift_Number_2_Button3_Map = $2EE7C + $078;
Lift_Number_2_Button3_Elevation = $2EE7C + $07C;
Lift_Number_2_Button3_Tile = $2EE7C + $080;
Lift_Number_2_Button4_Map = $2EE7C + $084;
Lift_Number_2_Button4_Elevation = $2EE7C + $088;
Lift_Number_2_Button4_Tile = $2EE7C + $08C;
Lift_Number_3_Button1_Map = $2EE7C + $090;
Lift_Number_3_Button1_Elevation = $2EE7C + $094;
Lift_Number_3_Button1_Tile = $2EE7C + $098;
Lift_Number_3_Button2_Map = $2EE7C + $09C;
Lift_Number_3_Button2_Elevation = $2EE7C + $0A0;
Lift_Number_3_Button2_Tile = $2EE7C + $0A4;
Lift_Number_3_Button3_Map = $2EE7C + $0A8;
Lift_Number_3_Button3_Elevation = $2EE7C + $0AC;
Lift_Number_3_Button3_Tile = $2EE7C + $0B0;
Lift_Number_3_Button4_Map = $2EE7C + $0B4;
Lift_Number_3_Button4_Elevation = $2EE7C + $0B8;
Lift_Number_3_Button4_Tile = $2EE7C + $0BC;
Lift_Number_4_Button1_Map = $2EE7C + $0C0;
Lift_Number_4_Button1_Elevation = $2EE7C + $0C4;
Lift_Number_4_Button1_Tile = $2EE7C + $0C8;
Lift_Number_4_Button2_Map = $2EE7C + $0CC;
Lift_Number_4_Button2_Elevation = $2EE7C + $0D0;
Lift_Number_4_Button2_Tile = $2EE7C + $0D4;
Lift_Number_4_Button3_Map = $2EE7C + $0D8;
Lift_Number_4_Button3_Elevation = $2EE7C + $0DC;
Lift_Number_4_Button3_Tile = $2EE7C + $0E0;
Lift_Number_4_Button4_Map = $2EE7C + $0E4;
Lift_Number_4_Button4_Elevation = $2EE7C + $0E8;
Lift_Number_4_Button4_Tile = $2EE7C + $0EC;
Lift_Number_5_Button1_Map = $2EE7C + $0F0;
Lift_Number_5_Button1_Elevation = $2EE7C + $0F4;
Lift_Number_5_Button1_Tile = $2EE7C + $0F8;
Lift_Number_5_Button2_Map = $2EE7C + $0FC;
Lift_Number_5_Button2_Elevation = $2EE7C + $100;
Lift_Number_5_Button2_Tile = $2EE7C + $104;
Lift_Number_5_Button3_Map = $2EE7C + $108;
Lift_Number_5_Button3_Elevation = $2EE7C + $10C;
Lift_Number_5_Button3_Tile = $2EE7C + $110;
Lift_Number_5_Button4_Map = $2EE7C + $114;
Lift_Number_5_Button4_Elevation = $2EE7C + $118;
Lift_Number_5_Button4_Tile = $2EE7C + $11C;
Lift_Number_6_Button1_Map = $2EE7C + $120;
Lift_Number_6_Button1_Elevation = $2EE7C + $124;
Lift_Number_6_Button1_Tile = $2EE7C + $128;
Lift_Number_6_Button2_Map = $2EE7C + $12C;
Lift_Number_6_Button2_Elevation = $2EE7C + $130;
Lift_Number_6_Button2_Tile = $2EE7C + $134;
Lift_Number_6_Button3_Map = $2EE7C + $138;
Lift_Number_6_Button3_Elevation = $2EE7C + $13C;
Lift_Number_6_Button3_Tile = $2EE7C + $140;
Lift_Number_6_Button4_Map = $2EE7C + $144;
Lift_Number_6_Button4_Elevation = $2EE7C + $148;
Lift_Number_6_Button4_Tile = $2EE7C + $14C;
Lift_Number_7_Button1_Map = $2EE7C + $150;
Lift_Number_7_Button1_Elevation = $2EE7C + $154;
Lift_Number_7_Button1_Tile = $2EE7C + $158;
Lift_Number_7_Button2_Map = $2EE7C + $15C;
Lift_Number_7_Button2_Elevation = $2EE7C + $160;
Lift_Number_7_Button2_Tile = $2EE7C + $164;
Lift_Number_7_Button3_Map = $2EE7C + $168;
Lift_Number_7_Button3_Elevation = $2EE7C + $16C;
Lift_Number_7_Button3_Tile = $2EE7C + $170;
Lift_Number_7_Button4_Map = $2EE7C + $174;
Lift_Number_7_Button4_Elevation = $2EE7C + $178;
Lift_Number_7_Button4_Tile = $2EE7C + $17C;
Lift_Number_8_Button1_Map = $2EE7C + $180;
Lift_Number_8_Button1_Elevation = $2EE7C + $184;
Lift_Number_8_Button1_Tile = $2EE7C + $188;
Lift_Number_8_Button2_Map = $2EE7C + $18C;
Lift_Number_8_Button2_Elevation = $2EE7C + $190;
Lift_Number_8_Button2_Tile = $2EE7C + $194;
Lift_Number_8_Button3_Map = $2EE7C + $198;
Lift_Number_8_Button3_Elevation = $2EE7C + $19C;
Lift_Number_8_Button3_Tile = $2EE7C + $1A0;
Lift_Number_8_Button4_Map = $2EE7C + $1A4;
Lift_Number_8_Button4_Elevation = $2EE7C + $1A8;
Lift_Number_8_Button4_Tile = $2EE7C + $1AC;
Lift_Number_9_Button1_Map = $2EE7C + $1B0;
Lift_Number_9_Button1_Elevation = $2EE7C + $1B4;
Lift_Number_9_Button1_Tile = $2EE7C + $1B8;
Lift_Number_9_Button2_Map = $2EE7C + $1BC;
Lift_Number_9_Button2_Elevation = $2EE7C + $1C0;
Lift_Number_9_Button2_Tile = $2EE7C + $1C4;
Lift_Number_9_Button3_Map = $2EE7C + $1C8;
Lift_Number_9_Button3_Elevation = $2EE7C + $1CC;
Lift_Number_9_Button3_Tile = $2EE7C + $1D0;
Lift_Number_9_Button4_Map = $2EE7C + $1D4;
Lift_Number_9_Button4_Elevation = $2EE7C + $1D8;
Lift_Number_9_Button4_Tile = $2EE7C + $1DC;
Lift_Number_10_Button1_Map = $2EE7C + $1E0;
Lift_Number_10_Button1_Elevation = $2EE7C + $1E4;
Lift_Number_10_Button1_Tile = $2EE7C + $1E8;
Lift_Number_10_Button2_Map = $2EE7C + $1EC;
Lift_Number_10_Button2_Elevation = $2EE7C + $1F0;
Lift_Number_10_Button2_Tile = $2EE7C + $1F4;
Lift_Number_10_Button3_Map = $2EE7C + $1F8;
Lift_Number_10_Button3_Elevation = $2EE7C + $1FC;
Lift_Number_10_Button3_Tile = $2EE7C + $200;
Lift_Number_10_Button4_Map = $2EE7C + $204;
Lift_Number_10_Button4_Elevation = $2EE7C + $208;
Lift_Number_10_Button4_Tile = $2EE7C + $20C;
Lift_Number_11_Button1_Map = $2EE7C + $210;
Lift_Number_11_Button1_Elevation = $2EE7C + $214;
Lift_Number_11_Button1_Tile = $2EE7C + $218;
Lift_Number_11_Button2_Map = $2EE7C + $21C;
Lift_Number_11_Button2_Elevation = $2EE7C + $220;
Lift_Number_11_Button2_Tile = $2EE7C + $224;
Lift_Number_11_Button3_Map = $2EE7C + $228;
Lift_Number_11_Button3_Elevation = $2EE7C + $22C;
Lift_Number_11_Button3_Tile = $2EE7C + $230;
Lift_Number_11_Button4_Map = $2EE7C + $234;
Lift_Number_11_Button4_Elevation = $2EE7C + $238;
Lift_Number_11_Button4_Tile = $2EE7C + $23C;
Lift_Number_12_Button1_Map = $2EE7C + $240;
Lift_Number_12_Button1_Elevation = $2EE7C + $244;
Lift_Number_12_Button1_Tile = $2EE7C + $248;
Lift_Number_12_Button2_Map = $2EE7C + $24C;
Lift_Number_12_Button2_Elevation = $2EE7C + $250;
Lift_Number_12_Button2_Tile = $2EE7C + $254;
Lift_Number_12_Button3_Map = $2EE7C + $258;
Lift_Number_12_Button3_Elevation = $2EE7C + $25C;
Lift_Number_12_Button3_Tile = $2EE7C + $260;
Lift_Number_12_Button4_Map = $2EE7C + $264;
Lift_Number_12_Button4_Elevation = $2EE7C + $268;
Lift_Number_12_Button4_Tile = $2EE7C + $26C;
Lift_Number_13_Button1_Map = $2EE7C + $270;
Lift_Number_13_Button1_Elevation = $2EE7C + $274;
Lift_Number_13_Button1_Tile = $2EE7C + $278;
Lift_Number_13_Button2_Map = $2EE7C + $27C;
Lift_Number_13_Button2_Elevation = $2EE7C + $280;
Lift_Number_13_Button2_Tile = $2EE7C + $284;
Lift_Number_13_Button3_Map = $2EE7C + $288;
Lift_Number_13_Button3_Elevation = $2EE7C + $28C;
Lift_Number_13_Button3_Tile = $2EE7C + $290;
Lift_Number_13_Button4_Map = $2EE7C + $294;
Lift_Number_13_Button4_Elevation = $2EE7C + $298;
Lift_Number_13_Button4_Tile = $2EE7C + $29C;
Lift_Number_14_Button1_Map = $2EE7C + $2A0;
Lift_Number_14_Button1_Elevation = $2EE7C + $2A4;
Lift_Number_14_Button1_Tile = $2EE7C + $2A8;
Lift_Number_14_Button2_Map = $2EE7C + $2AC;
Lift_Number_14_Button2_Elevation = $2EE7C + $2B0;
Lift_Number_14_Button2_Tile = $2EE7C + $2B4;
Lift_Number_14_Button3_Map = $2EE7C + $2B8;
Lift_Number_14_Button3_Elevation = $2EE7C + $2BC;
Lift_Number_14_Button3_Tile = $2EE7C + $2C0;
Lift_Number_14_Button4_Map = $2EE7C + $2C4;
Lift_Number_14_Button4_Elevation = $2EE7C + $2C8;
Lift_Number_14_Button4_Tile = $2EE7C + $2CC;
Lift_Number_15_Button1_Map = $2EE7C + $2D0;
Lift_Number_15_Button1_Elevation = $2EE7C + $2D4;
Lift_Number_15_Button1_Tile = $2EE7C + $2D8;
Lift_Number_15_Button2_Map = $2EE7C + $2DC;
Lift_Number_15_Button2_Elevation = $2EE7C + $2E0;
Lift_Number_15_Button2_Tile = $2EE7C + $2E4;
Lift_Number_15_Button3_Map = $2EE7C + $2E8;
Lift_Number_15_Button3_Elevation = $2EE7C + $2EC;
Lift_Number_15_Button3_Tile = $2EE7C + $2F0;
Lift_Number_15_Button4_Map = $2EE7C + $2F4;
Lift_Number_15_Button4_Elevation = $2EE7C + $2F8;
Lift_Number_15_Button4_Tile = $2EE7C + $2FC;
Lift_Number_16_Button1_Map = $2EE7C + $300;
Lift_Number_16_Button1_Elevation = $2EE7C + $304;
Lift_Number_16_Button1_Tile = $2EE7C + $308;
Lift_Number_16_Button2_Map = $2EE7C + $30C;
Lift_Number_16_Button2_Elevation = $2EE7C + $310;
Lift_Number_16_Button2_Tile = $2EE7C + $314;
Lift_Number_16_Button3_Map = $2EE7C + $318;
Lift_Number_16_Button3_Elevation = $2EE7C + $31C;
Lift_Number_16_Button3_Tile = $2EE7C + $320;
Lift_Number_16_Button4_Map = $2EE7C + $324;
Lift_Number_16_Button4_Elevation = $2EE7C + $328;
Lift_Number_16_Button4_Tile = $2EE7C + $32C;
Lift_Number_17_Button1_Map = $2EE7C + $330;
Lift_Number_17_Button1_Elevation = $2EE7C + $334;
Lift_Number_17_Button1_Tile = $2EE7C + $338;
Lift_Number_17_Button2_Map = $2EE7C + $33C;
Lift_Number_17_Button2_Elevation = $2EE7C + $340;
Lift_Number_17_Button2_Tile = $2EE7C + $344;
Lift_Number_17_Button3_Map = $2EE7C + $348;
Lift_Number_17_Button3_Elevation = $2EE7C + $34C;
Lift_Number_17_Button3_Tile = $2EE7C + $350;
Lift_Number_17_Button4_Map = $2EE7C + $354;
Lift_Number_17_Button4_Elevation = $2EE7C + $358;
Lift_Number_17_Button4_Tile = $2EE7C + $35C;
Lift_Number_18_Button1_Map = $2EE7C + $360;
Lift_Number_18_Button1_Elevation = $2EE7C + $364;
Lift_Number_18_Button1_Tile = $2EE7C + $368;
Lift_Number_18_Button2_Map = $2EE7C + $36C;
Lift_Number_18_Button2_Elevation = $2EE7C + $370;
Lift_Number_18_Button2_Tile = $2EE7C + $374;
Lift_Number_18_Button3_Map = $2EE7C + $378;
Lift_Number_18_Button3_Elevation = $2EE7C + $37C;
Lift_Number_18_Button3_Tile = $2EE7C + $380;
Lift_Number_18_Button4_Map = $2EE7C + $384;
Lift_Number_18_Button4_Elevation = $2EE7C + $388;
Lift_Number_18_Button4_Tile = $2EE7C + $38C;
Lift_Number_19_Button1_Map = $2EE7C + $390;
Lift_Number_19_Button1_Elevation = $2EE7C + $394;
Lift_Number_19_Button1_Tile = $2EE7C + $398;
Lift_Number_19_Button2_Map = $2EE7C + $39C;
Lift_Number_19_Button2_Elevation = $2EE7C + $3A0;
Lift_Number_19_Button2_Tile = $2EE7C + $3A4;
Lift_Number_19_Button3_Map = $2EE7C + $3A8;
Lift_Number_19_Button3_Elevation = $2EE7C + $3AC;
Lift_Number_19_Button3_Tile = $2EE7C + $3B0;
Lift_Number_19_Button4_Map = $2EE7C + $3B4;
Lift_Number_19_Button4_Elevation = $2EE7C + $3B8;
Lift_Number_19_Button4_Tile = $2EE7C + $3BC;
Lift_Number_20_Button1_Map = $2EE7C + $3C0;
Lift_Number_20_Button1_Elevation = $2EE7C + $3C4;
Lift_Number_20_Button1_Tile = $2EE7C + $3C8;
Lift_Number_20_Button2_Map = $2EE7C + $3CC;
Lift_Number_20_Button2_Elevation = $2EE7C + $3D0;
Lift_Number_20_Button2_Tile = $2EE7C + $3D4;
Lift_Number_20_Button3_Map = $2EE7C + $3D8;
Lift_Number_20_Button3_Elevation = $2EE7C + $3DC;
Lift_Number_20_Button3_Tile = $2EE7C + $3E0;
Lift_Number_20_Button4_Map = $2EE7C + $3E4;
Lift_Number_20_Button4_Elevation = $2EE7C + $3E8;
Lift_Number_20_Button4_Tile = $2EE7C + $3EC;
Lift_Number_21_Button1_Map = $2EE7C + $3F0;
Lift_Number_21_Button1_Elevation = $2EE7C + $3F4;
Lift_Number_21_Button1_Tile = $2EE7C + $3F8;
Lift_Number_21_Button2_Map = $2EE7C + $3FC;
Lift_Number_21_Button2_Elevation = $2EE7C + $400;
Lift_Number_21_Button2_Tile = $2EE7C + $404;
Lift_Number_21_Button3_Map = $2EE7C + $408;
Lift_Number_21_Button3_Elevation = $2EE7C + $40C;
Lift_Number_21_Button3_Tile = $2EE7C + $410;
Lift_Number_21_Button4_Map = $2EE7C + $414;
Lift_Number_21_Button4_Elevation = $2EE7C + $418;
Lift_Number_21_Button4_Tile = $2EE7C + $41C;
Lift_Number_22_Button1_Map = $2EE7C + $420;
Lift_Number_22_Button1_Elevation = $2EE7C + $424;
Lift_Number_22_Button1_Tile = $2EE7C + $428;
Lift_Number_22_Button2_Map = $2EE7C + $42C;
Lift_Number_22_Button2_Elevation = $2EE7C + $430;
Lift_Number_22_Button2_Tile = $2EE7C + $434;
Lift_Number_22_Button3_Map = $2EE7C + $438;
Lift_Number_22_Button3_Elevation = $2EE7C + $43C;
Lift_Number_22_Button3_Tile = $2EE7C + $440;
Lift_Number_22_Button4_Map = $2EE7C + $444;
Lift_Number_22_Button4_Elevation = $2EE7C + $448;
Lift_Number_22_Button4_Tile = $2EE7C + $44C;
Lift_Number_23_Button1_Map = $2EE7C + $450;
Lift_Number_23_Button1_Elevation = $2EE7C + $454;
Lift_Number_23_Button1_Tile = $2EE7C + $458;
Lift_Number_23_Button2_Map = $2EE7C + $45C;
Lift_Number_23_Button2_Elevation = $2EE7C + $460;
Lift_Number_23_Button2_Tile = $2EE7C + $464;
Lift_Number_23_Button3_Map = $2EE7C + $468;
Lift_Number_23_Button3_Elevation = $2EE7C + $46C;
Lift_Number_23_Button3_Tile = $2EE7C + $470;
Lift_Number_23_Button4_Map = $2EE7C + $474;
Lift_Number_23_Button4_Elevation = $2EE7C + $478;
Lift_Number_23_Button4_Tile = $2EE7C + $47C;

Lift_Number_0_Button_Count=$2EE1C + $000;
Lift_Number_1_Button_Count=$2EE1C + $004;
Lift_Number_2_Button_Count=$2EE1C + $008;
Lift_Number_3_Button_Count=$2EE1C + $00C;
Lift_Number_4_Button_Count=$2EE1C + $010;
Lift_Number_5_Button_Count=$2EE1C + $014;
Lift_Number_6_Button_Count=$2EE1C + $018;
Lift_Number_7_Button_Count=$2EE1C + $01C;
Lift_Number_8_Button_Count=$2EE1C + $020;
Lift_Number_9_Button_Count=$2EE1C + $024;
Lift_Number_10_Button_Count=$2EE1C + $028;
Lift_Number_11_Button_Count=$2EE1C + $02C;
Lift_Number_12_Button_Count=$2EE1C + $030;
Lift_Number_13_Button_Count=$2EE1C + $034;
Lift_Number_14_Button_Count=$2EE1C + $038;
Lift_Number_15_Button_Count=$2EE1C + $03C;
Lift_Number_16_Button_Count=$2EE1C + $040;
Lift_Number_17_Button_Count=$2EE1C + $044;
Lift_Number_18_Button_Count=$2EE1C + $048;
Lift_Number_19_Button_Count=$2EE1C + $04C;
Lift_Number_20_Button_Count=$2EE1C + $050;
Lift_Number_21_Button_Count=$2EE1C + $054;
Lift_Number_22_Button_Count=$2EE1C + $058;
Lift_Number_23_Button_Count=$2EE1C + $05C;

Lift_Number_0_Main_Frm_Number=$2ED5C + $000;
Lift_Number_0_Left_Frm_Number=$2ED5C + $004;
Lift_Number_1_Main_Frm_Number=$2ED5C + $008;
Lift_Number_1_Left_Frm_Number=$2ED5C + $00C;
Lift_Number_2_Main_Frm_Number=$2ED5C + $010;
Lift_Number_2_Left_Frm_Number=$2ED5C + $014;
Lift_Number_3_Main_Frm_Number=$2ED5C + $018;
Lift_Number_3_Left_Frm_Number=$2ED5C + $01C;
Lift_Number_4_Main_Frm_Number=$2ED5C + $020;
Lift_Number_4_Left_Frm_Number=$2ED5C + $024;
Lift_Number_5_Main_Frm_Number=$2ED5C + $028;
Lift_Number_5_Left_Frm_Number=$2ED5C + $02C;
Lift_Number_6_Main_Frm_Number=$2ED5C + $030;
Lift_Number_6_Left_Frm_Number=$2ED5C + $034;
Lift_Number_7_Main_Frm_Number=$2ED5C + $038;
Lift_Number_7_Left_Frm_Number=$2ED5C + $03C;
Lift_Number_8_Main_Frm_Number=$2ED5C + $040;
Lift_Number_8_Left_Frm_Number=$2ED5C + $044;
Lift_Number_9_Main_Frm_Number=$2ED5C + $048;
Lift_Number_9_Left_Frm_Number=$2ED5C + $04C;
Lift_Number_10_Main_Frm_Number=$2ED5C + $050;
Lift_Number_10_Left_Frm_Number=$2ED5C + $054;
Lift_Number_11_Main_Frm_Number=$2ED5C + $058;
Lift_Number_11_Left_Frm_Number=$2ED5C + $05C;
Lift_Number_12_Main_Frm_Number=$2ED5C + $060;
Lift_Number_12_Left_Frm_Number=$2ED5C + $064;
Lift_Number_13_Main_Frm_Number=$2ED5C + $068;
Lift_Number_13_Left_Frm_Number=$2ED5C + $06C;
Lift_Number_14_Main_Frm_Number=$2ED5C + $070;
Lift_Number_14_Left_Frm_Number=$2ED5C + $074;
Lift_Number_15_Main_Frm_Number=$2ED5C + $078;
Lift_Number_15_Left_Frm_Number=$2ED5C + $07C;
Lift_Number_16_Main_Frm_Number=$2ED5C + $080;
Lift_Number_16_Left_Frm_Number=$2ED5C + $084;
Lift_Number_17_Main_Frm_Number=$2ED5C + $088;
Lift_Number_17_Left_Frm_Number=$2ED5C + $08C;
Lift_Number_18_Main_Frm_Number=$2ED5C + $090;
Lift_Number_18_Left_Frm_Number=$2ED5C + $094;
Lift_Number_19_Main_Frm_Number=$2ED5C + $098;
Lift_Number_19_Left_Frm_Number=$2ED5C + $09C;
Lift_Number_20_Main_Frm_Number=$2ED5C + $0A0;
Lift_Number_20_Left_Frm_Number=$2ED5C + $0A4;
Lift_Number_21_Main_Frm_Number=$2ED5C + $0A8;
Lift_Number_21_Left_Frm_Number=$2ED5C + $0AC;
Lift_Number_22_Main_Frm_Number=$2ED5C + $0B0;
Lift_Number_22_Left_Frm_Number=$2ED5C + $0B4;
Lift_Number_23_Main_Frm_Number=$2ED5C + $0B8;
Lift_Number_23_Left_Frm_Number=$2ED5C + $0BC;

 
type
TBuf=array[0..$7FFFFFFE] of byte;
PBuf=^TBuf;

var
hin,hout:THandle;
buf:PBuf;
len,br:Dword;
filenamebuf:array[0..12] of byte;

begin
hin:=CreateFile('fallout2.exe',GENERIC_READ,FILE_SHARE_READ,nil,OPEN_EXISTING,FILE_FLAG_SEQUENTIAL_SCAN,0);
   if hin=INVALID_HANDLE_VALUE then
   begin
      //MessageBox(0,'fallout2.exe not found','',MB_OK);
      exit;
   end;
   len:=GetFileSize(hin,nil);
   buf:=GetMemory(len);
   ReadFile(hin,buf^,len,br,nil);
   CloseHandle(hin);

   //patching

//br:=GetPrivateProfileString('Patch','Starting_Map',nil,@filenamebuf,13,'.\patcher.txt');
//CopyMemory(@buf[$107ac8],@filenamebuf,br+1);

//br:=GetPrivateProfileString('Patch','Starting_Male',nil,@filenamebuf,13,'.\patcher.txt');
//CopyMemory(@buf[$ee8e8],@filenamebuf,br+1);

//br:=GetPrivateProfileString('Patch','Starting_Female',nil,@filenamebuf,13,'.\patcher.txt');
//CopyMemory(@buf[$ee8f0],@filenamebuf,br+1);

//br:=GetPrivateProfileString('Patch','Starting_Day',nil,@filenamebuf,13,'.\patcher.txt');
//CopyMemory(@buf[$93756],@filenamebuf,br+1);

//br:=GetPrivateProfileInt('Patch','Starting_Day',0,'.\patcher.txt');
//buf[$93756]:=br;

//br:=GetPrivateProfileInt('Patch','Starting_Year',0,'.\patcher.txt');
//CopyMemory(@buf[$9376C],@br,4);

//br:=GetPrivateProfileInt('Patch','Starting_Month',0,'.\patcher.txt');
//buf[$93782]:=br;



//br:=GetPrivateProfileInt('Patch','Starting_Pos_X',0,'.\patcher.txt');
//CopyMemory(@buf[$AD008],@br,4);

//br:=GetPrivateProfileInt('Patch','Starting_Pos_Y',0,'.\patcher.txt');
//CopyMemory(@buf[$AD00D],@br,4);

//br:=GetPrivateProfileInt('Patch','Starting_Pos_X',0,'.\patcher.txt');
//CopyMemory(@buf[$ACD90],@br,4);

//br:=GetPrivateProfileInt('Patch','Starting_Pos_Y',0,'.\patcher.txt');
//CopyMemory(@buf[$ACD95],@br,4);

//br:=GetPrivateProfileInt('Patch','Starting_View_X',0,'.\patcher.txt');
//CopyMemory(@buf[$10C42C],@br,4);

//br:=GetPrivateProfileInt('Patch','Starting_View_Y',0,'.\patcher.txt');
//CopyMemory(@buf[$10C430],@br,4);




br:=GetPrivateProfileInt('Lift_Number_0','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_0_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_0','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_0_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_0','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_0_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_0','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_0_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_0','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_0_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_0','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_0_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_0','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_0_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_0','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_0_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_0','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_0_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_0','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_0_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_0','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_0_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_0','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_0_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_1','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_1_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_1','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_1_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_1','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_1_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_1','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_1_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_1','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_1_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_1','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_1_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_1','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_1_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_1','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_1_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_1','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_1_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_1','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_1_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_1','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_1_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_1','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_1_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_2','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_2_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_2','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_2_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_2','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_2_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_2','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_2_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_2','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_2_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_2','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_2_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_2','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_2_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_2','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_2_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_2','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_2_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_2','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_2_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_2','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_2_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_2','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_2_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_3','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_3_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_3','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_3_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_3','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_3_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_3','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_3_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_3','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_3_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_3','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_3_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_3','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_3_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_3','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_3_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_3','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_3_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_3','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_3_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_3','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_3_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_3','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_3_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_4','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_4_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_4','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_4_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_4','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_4_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_4','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_4_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_4','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_4_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_4','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_4_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_4','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_4_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_4','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_4_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_4','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_4_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_4','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_4_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_4','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_4_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_4','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_4_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_5','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_5_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_5','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_5_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_5','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_5_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_5','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_5_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_5','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_5_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_5','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_5_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_5','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_5_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_5','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_5_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_5','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_5_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_5','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_5_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_5','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_5_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_5','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_5_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_6','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_6_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_6','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_6_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_6','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_6_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_6','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_6_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_6','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_6_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_6','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_6_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_6','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_6_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_6','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_6_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_6','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_6_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_6','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_6_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_6','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_6_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_6','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_6_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_7','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_7_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_7','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_7_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_7','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_7_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_7','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_7_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_7','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_7_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_7','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_7_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_7','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_7_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_7','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_7_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_7','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_7_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_7','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_7_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_7','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_7_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_7','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_7_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_8','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_8_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_8','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_8_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_8','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_8_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_8','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_8_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_8','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_8_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_8','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_8_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_8','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_8_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_8','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_8_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_8','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_8_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_8','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_8_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_8','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_8_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_8','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_8_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_9','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_9_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_9','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_9_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_9','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_9_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_9','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_9_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_9','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_9_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_9','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_9_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_9','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_9_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_9','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_9_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_9','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_9_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_9','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_9_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_9','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_9_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_9','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_9_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_10','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_10_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_10','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_10_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_10','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_10_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_10','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_10_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_10','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_10_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_10','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_10_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_10','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_10_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_10','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_10_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_10','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_10_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_10','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_10_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_10','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_10_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_10','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_10_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_11','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_11_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_11','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_11_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_11','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_11_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_11','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_11_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_11','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_11_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_11','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_11_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_11','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_11_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_11','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_11_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_11','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_11_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_11','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_11_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_11','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_11_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_11','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_11_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_12','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_12_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_12','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_12_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_12','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_12_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_12','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_12_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_12','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_12_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_12','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_12_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_12','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_12_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_12','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_12_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_12','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_12_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_12','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_12_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_12','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_12_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_12','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_12_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_13','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_13_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_13','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_13_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_13','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_13_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_13','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_13_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_13','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_13_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_13','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_13_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_13','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_13_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_13','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_13_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_13','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_13_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_13','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_13_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_13','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_13_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_13','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_13_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_14','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_14_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_14','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_14_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_14','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_14_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_14','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_14_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_14','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_14_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_14','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_14_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_14','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_14_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_14','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_14_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_14','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_14_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_14','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_14_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_14','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_14_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_14','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_14_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_15','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_15_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_15','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_15_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_15','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_15_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_15','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_15_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_15','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_15_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_15','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_15_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_15','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_15_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_15','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_15_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_15','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_15_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_15','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_15_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_15','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_15_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_15','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_15_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_16','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_16_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_16','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_16_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_16','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_16_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_16','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_16_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_16','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_16_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_16','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_16_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_16','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_16_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_16','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_16_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_16','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_16_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_16','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_16_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_16','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_16_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_16','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_16_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_17','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_17_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_17','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_17_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_17','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_17_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_17','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_17_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_17','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_17_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_17','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_17_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_17','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_17_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_17','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_17_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_17','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_17_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_17','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_17_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_17','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_17_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_17','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_17_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_18','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_18_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_18','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_18_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_18','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_18_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_18','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_18_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_18','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_18_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_18','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_18_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_18','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_18_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_18','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_18_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_18','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_18_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_18','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_18_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_18','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_18_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_18','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_18_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_19','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_19_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_19','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_19_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_19','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_19_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_19','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_19_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_19','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_19_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_19','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_19_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_19','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_19_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_19','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_19_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_19','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_19_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_19','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_19_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_19','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_19_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_19','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_19_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_20','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_20_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_20','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_20_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_20','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_20_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_20','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_20_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_20','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_20_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_20','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_20_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_20','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_20_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_20','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_20_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_20','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_20_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_20','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_20_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_20','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_20_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_20','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_20_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_21','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_21_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_21','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_21_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_21','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_21_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_21','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_21_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_21','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_21_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_21','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_21_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_21','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_21_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_21','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_21_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_21','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_21_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_21','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_21_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_21','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_21_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_21','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_21_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_22','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_22_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_22','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_22_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_22','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_22_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_22','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_22_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_22','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_22_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_22','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_22_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_22','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_22_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_22','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_22_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_22','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_22_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_22','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_22_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_22','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_22_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_22','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_22_Button4_Tile],@br,5);

br:=GetPrivateProfileInt('Lift_Number_23','Button1_Map',0,'.\patcher.txt');
buf[Lift_Number_23_Button1_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_23','Button1_Elevation',0,'.\patcher.txt');
buf[Lift_Number_23_Button1_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_23','Button1_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_23_Button1_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_23','Button2_Map',0,'.\patcher.txt');
buf[Lift_Number_23_Button2_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_23','Button2_Elevation',0,'.\patcher.txt');
buf[Lift_Number_23_Button2_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_23','Button2_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_23_Button2_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_23','Button3_Map',0,'.\patcher.txt');
buf[Lift_Number_23_Button3_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_23','Button3_Elevation',0,'.\patcher.txt');
buf[Lift_Number_23_Button3_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_23','Button3_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_23_Button3_Tile],@br,5);
br:=GetPrivateProfileInt('Lift_Number_23','Button4_Map',0,'.\patcher.txt');
buf[Lift_Number_23_Button4_Map]:=br;
br:=GetPrivateProfileInt('Lift_Number_23','Button4_Elevation',0,'.\patcher.txt');
buf[Lift_Number_23_Button4_Elevation]:=br;
br:=GetPrivateProfileInt('Lift_Number_23','Button4_Tile',0,'.\patcher.txt');
CopyMemory(@buf[Lift_Number_23_Button4_Tile],@br,5);

//

br:=GetPrivateProfileInt('Lift_Number_0','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_0_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_0','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_0_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_0','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_0_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_1','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_1_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_1','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_1_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_1','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_1_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_2','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_2_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_2','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_2_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_2','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_2_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_3','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_3_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_3','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_3_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_3','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_3_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_4','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_4_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_4','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_4_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_4','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_4_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_5','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_5_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_5','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_5_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_5','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_5_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_6','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_6_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_6','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_6_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_6','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_6_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_7','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_7_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_7','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_7_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_7','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_7_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_8','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_8_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_8','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_8_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_8','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_8_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_9','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_9_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_9','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_9_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_9','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_9_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_10','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_10_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_10','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_10_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_10','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_10_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_11','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_11_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_11','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_11_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_11','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_11_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_12','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_12_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_12','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_12_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_12','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_12_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_13','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_13_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_13','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_13_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_13','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_13_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_14','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_14_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_14','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_14_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_14','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_14_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_15','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_15_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_15','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_15_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_15','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_15_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_16','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_16_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_16','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_16_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_16','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_16_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_17','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_17_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_17','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_17_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_17','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_17_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_18','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_18_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_18','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_18_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_18','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_18_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_19','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_19_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_19','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_19_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_19','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_19_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_20','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_20_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_20','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_20_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_20','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_20_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_21','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_21_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_21','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_21_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_21','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_21_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_22','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_22_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_22','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_22_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_22','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_22_Button_Count]:=br;

br:=GetPrivateProfileInt('Lift_Number_23','Main_Frm_Number',0,'.\patcher.txt');
buf[Lift_Number_23_Main_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_23','Left_Frm_Number',$FF,'.\patcher.txt');
buf[Lift_Number_23_Left_Frm_Number]:=br;
br:=GetPrivateProfileInt('Lift_Number_23','Button_Count',0,'.\patcher.txt');
buf[Lift_Number_23_Button_Count]:=br;

//Выключить сны
buf[$93B0F]:=$E9;
buf[$93B10]:=$95;
buf[$93B11]:=$00;
buf[$93B14]:=$90;
buf[$93BB7]:=$EB;

//Выключить видео
//buf[$3ea90]:=$c3;

// sfall.dll
//buf[$FE150]:=$53; //s
//buf[$FE151]:=$46; //f
//buf[$FE152]:=$41; //a
//buf[$FE153]:=$4C; //l
//buf[$FE154]:=$4C; //l
//buf[$FE155]:=$2E; //.
//buf[$FE156]:=$44; //d
//buf[$FE157]:=$4C; //l
//buf[$FE158]:=$4C; //l




   hout:=CreateFile('fallout.exe',GENERIC_WRITE,0,nil,CREATE_ALWAYS,0,0);
   if hout=INVALID_HANDLE_VALUE then
   begin
      //MessageBox(0,'cann''t create result file','',MB_OK);
      FreeMemory(buf);
      exit;
   end
   else
   begin
      WriteFile(hout,buf^,len,br,nil);
      CloseHandle(hout);
      //MessageBox(0,'fallout2.exe patch completed!'#13#10'patch result file: fallout.exe','',MB_OK);
   end;

   FreeMemory(buf);
end.
